// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package contentservice

import (
	"context"

	"zfeed/app/rpc/content/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticlePublishReq = content.ArticlePublishReq
	ArticlePublishRes = content.ArticlePublishRes
	VideoPublishReq   = content.VideoPublishReq
	VideoPublishRes   = content.VideoPublishRes

	ContentService interface {
		PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error)
		PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error)
	}

	defaultContentService struct {
		cli zrpc.Client
	}
)

func NewContentService(cli zrpc.Client) ContentService {
	return &defaultContentService{
		cli: cli,
	}
}

func (m *defaultContentService) PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishArticle(ctx, in, opts...)
}

func (m *defaultContentService) PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}
