CREATE TABLE IF NOT EXISTS `zfeed_article` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content_id` BIGINT NOT NULL,
  `title` VARCHAR(100) NOT NULL DEFAULT '',
  `description` VARCHAR(255) DEFAULT NULL,
  `cover` VARCHAR(1024) NOT NULL DEFAULT '',
  `content` LONGTEXT NOT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_content_id` (`content_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
