// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package favoriteservice

import (
	"context"

	"zfeed/app/rpc/interaction/interaction"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetCommentsReq   = interaction.BatchGetCommentsReq
	BatchGetCommentsRes   = interaction.BatchGetCommentsRes
	BatchQueryIsLikedReq  = interaction.BatchQueryIsLikedReq
	BatchQueryIsLikedRes  = interaction.BatchQueryIsLikedRes
	BatchQueryLikeInfoReq = interaction.BatchQueryLikeInfoReq
	BatchQueryLikeInfoRes = interaction.BatchQueryLikeInfoRes
	CommentItem           = interaction.CommentItem
	CommentReq            = interaction.CommentReq
	CommentRes            = interaction.CommentRes
	DeleteCommentReq      = interaction.DeleteCommentReq
	DeleteCommentRes      = interaction.DeleteCommentRes
	FavoriteItem          = interaction.FavoriteItem
	FavoriteReq           = interaction.FavoriteReq
	FavoriteRes           = interaction.FavoriteRes
	FollowUserReq         = interaction.FollowUserReq
	FollowUserRes         = interaction.FollowUserRes
	FollowerProfile       = interaction.FollowerProfile
	GetFollowSummaryReq   = interaction.GetFollowSummaryReq
	GetFollowSummaryRes   = interaction.GetFollowSummaryRes
	IsLikedInfo           = interaction.IsLikedInfo
	LikeInfo              = interaction.LikeInfo
	LikeReq               = interaction.LikeReq
	LikeRes               = interaction.LikeRes
	ListFolloweesReq      = interaction.ListFolloweesReq
	ListFolloweesRes      = interaction.ListFolloweesRes
	ListFollowersReq      = interaction.ListFollowersReq
	ListFollowersRes      = interaction.ListFollowersRes
	PageReq               = interaction.PageReq
	PageRes               = interaction.PageRes
	QueryCommentListReq   = interaction.QueryCommentListReq
	QueryCommentListRes   = interaction.QueryCommentListRes
	QueryFavoriteInfoReq  = interaction.QueryFavoriteInfoReq
	QueryFavoriteInfoRes  = interaction.QueryFavoriteInfoRes
	QueryFavoriteListReq  = interaction.QueryFavoriteListReq
	QueryFavoriteListRes  = interaction.QueryFavoriteListRes
	QueryLikeInfoReq      = interaction.QueryLikeInfoReq
	QueryLikeInfoRes      = interaction.QueryLikeInfoRes
	QueryReplyListReq     = interaction.QueryReplyListReq
	QueryReplyListRes     = interaction.QueryReplyListRes
	RefillCommentCacheReq = interaction.RefillCommentCacheReq
	RefillCommentCacheRes = interaction.RefillCommentCacheRes
	RemoveFavoriteReq     = interaction.RemoveFavoriteReq
	RemoveFavoriteRes     = interaction.RemoveFavoriteRes
	UnfollowUserReq       = interaction.UnfollowUserReq
	UnfollowUserRes       = interaction.UnfollowUserRes
	UnlikeReq             = interaction.UnlikeReq
	UnlikeRes             = interaction.UnlikeRes

	FavoriteService interface {
		Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteRes, error)
		RemoveFavorite(ctx context.Context, in *RemoveFavoriteReq, opts ...grpc.CallOption) (*RemoveFavoriteRes, error)
		QueryFavoriteInfo(ctx context.Context, in *QueryFavoriteInfoReq, opts ...grpc.CallOption) (*QueryFavoriteInfoRes, error)
		QueryFavoriteList(ctx context.Context, in *QueryFavoriteListReq, opts ...grpc.CallOption) (*QueryFavoriteListRes, error)
	}

	defaultFavoriteService struct {
		cli zrpc.Client
	}
)

func NewFavoriteService(cli zrpc.Client) FavoriteService {
	return &defaultFavoriteService{
		cli: cli,
	}
}

func (m *defaultFavoriteService) Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteRes, error) {
	client := interaction.NewFavoriteServiceClient(m.cli.Conn())
	return client.Favorite(ctx, in, opts...)
}

func (m *defaultFavoriteService) RemoveFavorite(ctx context.Context, in *RemoveFavoriteReq, opts ...grpc.CallOption) (*RemoveFavoriteRes, error) {
	client := interaction.NewFavoriteServiceClient(m.cli.Conn())
	return client.RemoveFavorite(ctx, in, opts...)
}

func (m *defaultFavoriteService) QueryFavoriteInfo(ctx context.Context, in *QueryFavoriteInfoReq, opts ...grpc.CallOption) (*QueryFavoriteInfoRes, error) {
	client := interaction.NewFavoriteServiceClient(m.cli.Conn())
	return client.QueryFavoriteInfo(ctx, in, opts...)
}

func (m *defaultFavoriteService) QueryFavoriteList(ctx context.Context, in *QueryFavoriteListReq, opts ...grpc.CallOption) (*QueryFavoriteListRes, error) {
	client := interaction.NewFavoriteServiceClient(m.cli.Conn())
	return client.QueryFavoriteList(ctx, in, opts...)
}
