// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	content "zfeed/app/front/internal/handler/content"
	feed "zfeed/app/front/internal/handler/feed"
	interaction "zfeed/app/front/internal/handler/interaction"
	user "zfeed/app/front/internal/handler/user"
	"zfeed/app/front/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserLoginStatusAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/:content_id",
					Handler: content.DeleteContentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/article/publish",
					Handler: content.PublishArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload-credentials",
					Handler: content.ContentUploadsCredentialsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/video/publish",
					Handler: content.PublishVideoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/content"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OptionalLoginMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/detail",
					Handler: content.GetContentDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/content"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OptionalLoginMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/follow",
					Handler: feed.FollowHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/recommend",
					Handler: feed.RecommendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/favorite",
					Handler: feed.UserFavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/publish",
					Handler: feed.UserPublishHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/feed"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/comment/list",
				Handler: interaction.QueryCommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/reply/list",
				Handler: interaction.QueryReplyCommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/favorite/info",
				Handler: interaction.QueryFavoriteInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/like/info",
				Handler: interaction.QueryLikeInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/like/info/batch",
				Handler: interaction.BatchQueryLikeInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/interaction"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserLoginStatusAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/comment",
					Handler: interaction.CommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/comment",
					Handler: interaction.DeleteCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/favorite",
					Handler: interaction.FavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/favorite",
					Handler: interaction.RemoveFavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/followings",
					Handler: interaction.FollowUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/followings",
					Handler: interaction.UnFollowUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/like",
					Handler: interaction.LikeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/unlike",
					Handler: interaction.UnlikeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/interaction"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/avatar/upload",
				Handler: user.UploadAvatarHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserLoginStatusAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/profile/:userId",
					Handler: user.QueryUserProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/me",
					Handler: user.GetMeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
