// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package server

import (
	"context"

	"zfeed/app/rpc/interaction/interaction"
	"zfeed/app/rpc/interaction/internal/logic/commentservice"
	"zfeed/app/rpc/interaction/internal/svc"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServiceServer) Comment(ctx context.Context, in *interaction.CommentReq) (*interaction.CommentRes, error) {
	l := commentservicelogic.NewCommentLogic(ctx, s.svcCtx)
	return l.Comment(in)
}

func (s *CommentServiceServer) DeleteComment(ctx context.Context, in *interaction.DeleteCommentReq) (*interaction.DeleteCommentRes, error) {
	l := commentservicelogic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *CommentServiceServer) QueryCommentList(ctx context.Context, in *interaction.QueryCommentListReq) (*interaction.QueryCommentListRes, error) {
	l := commentservicelogic.NewQueryCommentListLogic(ctx, s.svcCtx)
	return l.QueryCommentList(in)
}

func (s *CommentServiceServer) QueryReplyList(ctx context.Context, in *interaction.QueryReplyListReq) (*interaction.QueryReplyListRes, error) {
	l := commentservicelogic.NewQueryReplyListLogic(ctx, s.svcCtx)
	return l.QueryReplyList(in)
}

func (s *CommentServiceServer) BatchGetComments(ctx context.Context, in *interaction.BatchGetCommentsReq) (*interaction.BatchGetCommentsRes, error) {
	l := commentservicelogic.NewBatchGetCommentsLogic(ctx, s.svcCtx)
	return l.BatchGetComments(in)
}

func (s *CommentServiceServer) RefillCommentCache(ctx context.Context, in *interaction.RefillCommentCacheReq) (*interaction.RefillCommentCacheRes, error) {
	l := commentservicelogic.NewRefillCommentCacheLogic(ctx, s.svcCtx)
	return l.RefillCommentCache(in)
}
