// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: count.proto

package counterservice

import (
	"context"

	"zfeed/app/rpc/count/count"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetCountReq        = count.BatchGetCountReq
	BatchGetCountRes        = count.BatchGetCountRes
	CountKey                = count.CountKey
	CountValueItem          = count.CountValueItem
	DecReq                  = count.DecReq
	DecRes                  = count.DecRes
	GetCountReq             = count.GetCountReq
	GetCountRes             = count.GetCountRes
	GetUserProfileCountsReq = count.GetUserProfileCountsReq
	GetUserProfileCountsRes = count.GetUserProfileCountsRes
	IncReq                  = count.IncReq
	IncRes                  = count.IncRes

	CounterService interface {
		GetCount(ctx context.Context, in *GetCountReq, opts ...grpc.CallOption) (*GetCountRes, error)
		BatchGetCount(ctx context.Context, in *BatchGetCountReq, opts ...grpc.CallOption) (*BatchGetCountRes, error)
		Inc(ctx context.Context, in *IncReq, opts ...grpc.CallOption) (*IncRes, error)
		Dec(ctx context.Context, in *DecReq, opts ...grpc.CallOption) (*DecRes, error)
		GetUserProfileCounts(ctx context.Context, in *GetUserProfileCountsReq, opts ...grpc.CallOption) (*GetUserProfileCountsRes, error)
	}

	defaultCounterService struct {
		cli zrpc.Client
	}
)

func NewCounterService(cli zrpc.Client) CounterService {
	return &defaultCounterService{
		cli: cli,
	}
}

func (m *defaultCounterService) GetCount(ctx context.Context, in *GetCountReq, opts ...grpc.CallOption) (*GetCountRes, error) {
	client := count.NewCounterServiceClient(m.cli.Conn())
	return client.GetCount(ctx, in, opts...)
}

func (m *defaultCounterService) BatchGetCount(ctx context.Context, in *BatchGetCountReq, opts ...grpc.CallOption) (*BatchGetCountRes, error) {
	client := count.NewCounterServiceClient(m.cli.Conn())
	return client.BatchGetCount(ctx, in, opts...)
}

func (m *defaultCounterService) Inc(ctx context.Context, in *IncReq, opts ...grpc.CallOption) (*IncRes, error) {
	client := count.NewCounterServiceClient(m.cli.Conn())
	return client.Inc(ctx, in, opts...)
}

func (m *defaultCounterService) Dec(ctx context.Context, in *DecReq, opts ...grpc.CallOption) (*DecRes, error) {
	client := count.NewCounterServiceClient(m.cli.Conn())
	return client.Dec(ctx, in, opts...)
}

func (m *defaultCounterService) GetUserProfileCounts(ctx context.Context, in *GetUserProfileCountsReq, opts ...grpc.CallOption) (*GetUserProfileCountsRes, error) {
	client := count.NewCounterServiceClient(m.cli.Conn())
	return client.GetUserProfileCounts(ctx, in, opts...)
}
