// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package server

import (
	"context"

	"zfeed/app/rpc/interaction/interaction"
	"zfeed/app/rpc/interaction/internal/logic/likeservice"
	"zfeed/app/rpc/interaction/internal/svc"
)

type LikeServiceServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedLikeServiceServer
}

func NewLikeServiceServer(svcCtx *svc.ServiceContext) *LikeServiceServer {
	return &LikeServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServiceServer) Like(ctx context.Context, in *interaction.LikeReq) (*interaction.LikeRes, error) {
	l := likeservicelogic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

func (s *LikeServiceServer) Unlike(ctx context.Context, in *interaction.UnlikeReq) (*interaction.UnlikeRes, error) {
	l := likeservicelogic.NewUnlikeLogic(ctx, s.svcCtx)
	return l.Unlike(in)
}

func (s *LikeServiceServer) QueryLikeInfo(ctx context.Context, in *interaction.QueryLikeInfoReq) (*interaction.QueryLikeInfoRes, error) {
	l := likeservicelogic.NewQueryLikeInfoLogic(ctx, s.svcCtx)
	return l.QueryLikeInfo(in)
}

func (s *LikeServiceServer) BatchQueryLikeInfo(ctx context.Context, in *interaction.BatchQueryLikeInfoReq) (*interaction.BatchQueryLikeInfoRes, error) {
	l := likeservicelogic.NewBatchQueryLikeInfoLogic(ctx, s.svcCtx)
	return l.BatchQueryLikeInfo(in)
}

func (s *LikeServiceServer) BatchQueryIsLiked(ctx context.Context, in *interaction.BatchQueryIsLikedReq) (*interaction.BatchQueryIsLikedRes, error) {
	l := likeservicelogic.NewBatchQueryIsLikedLogic(ctx, s.svcCtx)
	return l.BatchQueryIsLiked(in)
}
