// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package server

import (
	"context"

	"zfeed/app/rpc/interaction/interaction"
	"zfeed/app/rpc/interaction/internal/logic/follow"
	"zfeed/app/rpc/interaction/internal/svc"
)

type FollowServiceServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedFollowServiceServer
}

func NewFollowServiceServer(svcCtx *svc.ServiceContext) *FollowServiceServer {
	return &FollowServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServiceServer) FollowUser(ctx context.Context, in *interaction.FollowUserReq) (*interaction.FollowUserRes, error) {
	l := followlogic.NewFollowUserLogic(ctx, s.svcCtx)
	return l.FollowUser(in)
}

func (s *FollowServiceServer) UnfollowUser(ctx context.Context, in *interaction.UnfollowUserReq) (*interaction.UnfollowUserRes, error) {
	l := followlogic.NewUnfollowUserLogic(ctx, s.svcCtx)
	return l.UnfollowUser(in)
}

func (s *FollowServiceServer) ListFollowees(ctx context.Context, in *interaction.ListFolloweesReq) (*interaction.ListFolloweesRes, error) {
	l := followlogic.NewListFolloweesLogic(ctx, s.svcCtx)
	return l.ListFollowees(in)
}

func (s *FollowServiceServer) ListFollowers(ctx context.Context, in *interaction.ListFollowersReq) (*interaction.ListFollowersRes, error) {
	l := followlogic.NewListFollowersLogic(ctx, s.svcCtx)
	return l.ListFollowers(in)
}

func (s *FollowServiceServer) BatchQueryFollowing(ctx context.Context, in *interaction.BatchQueryFollowingReq) (*interaction.BatchQueryFollowingRes, error) {
	l := followlogic.NewBatchQueryFollowingLogic(ctx, s.svcCtx)
	return l.BatchQueryFollowing(in)
}

func (s *FollowServiceServer) GetFollowSummary(ctx context.Context, in *interaction.GetFollowSummaryReq) (*interaction.GetFollowSummaryRes, error) {
	l := followlogic.NewGetFollowSummaryLogic(ctx, s.svcCtx)
	return l.GetFollowSummary(in)
}
