// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package server

import (
	"context"

	"zfeed/app/rpc/interaction/interaction"
	"zfeed/app/rpc/interaction/internal/logic/like"
	"zfeed/app/rpc/interaction/internal/svc"
)

type LikeServiceServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedLikeServiceServer
}

func NewLikeServiceServer(svcCtx *svc.ServiceContext) *LikeServiceServer {
	return &LikeServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServiceServer) Like(ctx context.Context, in *interaction.LikeReq) (*interaction.LikeRes, error) {
	l := likelogic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

func (s *LikeServiceServer) Unlike(ctx context.Context, in *interaction.UnlikeReq) (*interaction.UnlikeRes, error) {
	l := likelogic.NewUnlikeLogic(ctx, s.svcCtx)
	return l.Unlike(in)
}

func (s *LikeServiceServer) QueryLikeInfo(ctx context.Context, in *interaction.QueryLikeInfoReq) (*interaction.QueryLikeInfoRes, error) {
	l := likelogic.NewQueryLikeInfoLogic(ctx, s.svcCtx)
	return l.QueryLikeInfo(in)
}

func (s *LikeServiceServer) BatchLikeInfo(ctx context.Context, in *interaction.BatchLikeInfoReq) (*interaction.BatchLikeInfoRes, error) {
	l := likelogic.NewBatchLikeInfoLogic(ctx, s.svcCtx)
	return l.BatchLikeInfo(in)
}

func (s *LikeServiceServer) BatchIsLiked(ctx context.Context, in *interaction.BatchIsLikedReq) (*interaction.BatchIsLikedRes, error) {
	l := likelogic.NewBatchIsLikedLogic(ctx, s.svcCtx)
	return l.BatchIsLiked(in)
}
