// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: interaction.proto

package interaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LikeService_Like_FullMethodName               = "/interaction.LikeService/Like"
	LikeService_Unlike_FullMethodName             = "/interaction.LikeService/Unlike"
	LikeService_QueryLikeInfo_FullMethodName      = "/interaction.LikeService/QueryLikeInfo"
	LikeService_BatchQueryLikeInfo_FullMethodName = "/interaction.LikeService/BatchQueryLikeInfo"
	LikeService_BatchQueryIsLiked_FullMethodName  = "/interaction.LikeService/BatchQueryIsLiked"
)

// LikeServiceClient is the client API for LikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikeServiceClient interface {
	Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeRes, error)
	Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeRes, error)
	QueryLikeInfo(ctx context.Context, in *QueryLikeInfoReq, opts ...grpc.CallOption) (*QueryLikeInfoRes, error)
	BatchQueryLikeInfo(ctx context.Context, in *BatchQueryLikeInfoReq, opts ...grpc.CallOption) (*BatchQueryLikeInfoRes, error)
	BatchQueryIsLiked(ctx context.Context, in *BatchQueryIsLikedReq, opts ...grpc.CallOption) (*BatchQueryIsLikedRes, error)
}

type likeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeServiceClient(cc grpc.ClientConnInterface) LikeServiceClient {
	return &likeServiceClient{cc}
}

func (c *likeServiceClient) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeRes)
	err := c.cc.Invoke(ctx, LikeService_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikeRes)
	err := c.cc.Invoke(ctx, LikeService_Unlike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) QueryLikeInfo(ctx context.Context, in *QueryLikeInfoReq, opts ...grpc.CallOption) (*QueryLikeInfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLikeInfoRes)
	err := c.cc.Invoke(ctx, LikeService_QueryLikeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) BatchQueryLikeInfo(ctx context.Context, in *BatchQueryLikeInfoReq, opts ...grpc.CallOption) (*BatchQueryLikeInfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchQueryLikeInfoRes)
	err := c.cc.Invoke(ctx, LikeService_BatchQueryLikeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) BatchQueryIsLiked(ctx context.Context, in *BatchQueryIsLikedReq, opts ...grpc.CallOption) (*BatchQueryIsLikedRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchQueryIsLikedRes)
	err := c.cc.Invoke(ctx, LikeService_BatchQueryIsLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeServiceServer is the server API for LikeService service.
// All implementations must embed UnimplementedLikeServiceServer
// for forward compatibility.
type LikeServiceServer interface {
	Like(context.Context, *LikeReq) (*LikeRes, error)
	Unlike(context.Context, *UnlikeReq) (*UnlikeRes, error)
	QueryLikeInfo(context.Context, *QueryLikeInfoReq) (*QueryLikeInfoRes, error)
	BatchQueryLikeInfo(context.Context, *BatchQueryLikeInfoReq) (*BatchQueryLikeInfoRes, error)
	BatchQueryIsLiked(context.Context, *BatchQueryIsLikedReq) (*BatchQueryIsLikedRes, error)
	mustEmbedUnimplementedLikeServiceServer()
}

// UnimplementedLikeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLikeServiceServer struct{}

func (UnimplementedLikeServiceServer) Like(context.Context, *LikeReq) (*LikeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedLikeServiceServer) Unlike(context.Context, *UnlikeReq) (*UnlikeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlike not implemented")
}
func (UnimplementedLikeServiceServer) QueryLikeInfo(context.Context, *QueryLikeInfoReq) (*QueryLikeInfoRes, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryLikeInfo not implemented")
}
func (UnimplementedLikeServiceServer) BatchQueryLikeInfo(context.Context, *BatchQueryLikeInfoReq) (*BatchQueryLikeInfoRes, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchQueryLikeInfo not implemented")
}
func (UnimplementedLikeServiceServer) BatchQueryIsLiked(context.Context, *BatchQueryIsLikedReq) (*BatchQueryIsLikedRes, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchQueryIsLiked not implemented")
}
func (UnimplementedLikeServiceServer) mustEmbedUnimplementedLikeServiceServer() {}
func (UnimplementedLikeServiceServer) testEmbeddedByValue()                     {}

// UnsafeLikeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeServiceServer will
// result in compilation errors.
type UnsafeLikeServiceServer interface {
	mustEmbedUnimplementedLikeServiceServer()
}

func RegisterLikeServiceServer(s grpc.ServiceRegistrar, srv LikeServiceServer) {
	// If the following call panics, it indicates UnimplementedLikeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LikeService_ServiceDesc, srv)
}

func _LikeService_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).Like(ctx, req.(*LikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_Unlike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).Unlike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_Unlike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).Unlike(ctx, req.(*UnlikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_QueryLikeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLikeInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).QueryLikeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_QueryLikeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).QueryLikeInfo(ctx, req.(*QueryLikeInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_BatchQueryLikeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchQueryLikeInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).BatchQueryLikeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_BatchQueryLikeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).BatchQueryLikeInfo(ctx, req.(*BatchQueryLikeInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_BatchQueryIsLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchQueryIsLikedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).BatchQueryIsLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_BatchQueryIsLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).BatchQueryIsLiked(ctx, req.(*BatchQueryIsLikedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LikeService_ServiceDesc is the grpc.ServiceDesc for LikeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LikeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.LikeService",
	HandlerType: (*LikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Like",
			Handler:    _LikeService_Like_Handler,
		},
		{
			MethodName: "Unlike",
			Handler:    _LikeService_Unlike_Handler,
		},
		{
			MethodName: "QueryLikeInfo",
			Handler:    _LikeService_QueryLikeInfo_Handler,
		},
		{
			MethodName: "BatchQueryLikeInfo",
			Handler:    _LikeService_BatchQueryLikeInfo_Handler,
		},
		{
			MethodName: "BatchQueryIsLiked",
			Handler:    _LikeService_BatchQueryIsLiked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}

const (
	FavoriteService_Favorite_FullMethodName          = "/interaction.FavoriteService/Favorite"
	FavoriteService_RemoveFavorite_FullMethodName    = "/interaction.FavoriteService/RemoveFavorite"
	FavoriteService_QueryFavoriteInfo_FullMethodName = "/interaction.FavoriteService/QueryFavoriteInfo"
	FavoriteService_QueryFavoriteList_FullMethodName = "/interaction.FavoriteService/QueryFavoriteList"
)

// FavoriteServiceClient is the client API for FavoriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FavoriteServiceClient interface {
	Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteRes, error)
	RemoveFavorite(ctx context.Context, in *RemoveFavoriteReq, opts ...grpc.CallOption) (*RemoveFavoriteRes, error)
	QueryFavoriteInfo(ctx context.Context, in *QueryFavoriteInfoReq, opts ...grpc.CallOption) (*QueryFavoriteInfoRes, error)
	QueryFavoriteList(ctx context.Context, in *QueryFavoriteListReq, opts ...grpc.CallOption) (*QueryFavoriteListRes, error)
}

type favoriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFavoriteServiceClient(cc grpc.ClientConnInterface) FavoriteServiceClient {
	return &favoriteServiceClient{cc}
}

func (c *favoriteServiceClient) Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FavoriteRes)
	err := c.cc.Invoke(ctx, FavoriteService_Favorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) RemoveFavorite(ctx context.Context, in *RemoveFavoriteReq, opts ...grpc.CallOption) (*RemoveFavoriteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFavoriteRes)
	err := c.cc.Invoke(ctx, FavoriteService_RemoveFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) QueryFavoriteInfo(ctx context.Context, in *QueryFavoriteInfoReq, opts ...grpc.CallOption) (*QueryFavoriteInfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFavoriteInfoRes)
	err := c.cc.Invoke(ctx, FavoriteService_QueryFavoriteInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) QueryFavoriteList(ctx context.Context, in *QueryFavoriteListReq, opts ...grpc.CallOption) (*QueryFavoriteListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFavoriteListRes)
	err := c.cc.Invoke(ctx, FavoriteService_QueryFavoriteList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FavoriteServiceServer is the server API for FavoriteService service.
// All implementations must embed UnimplementedFavoriteServiceServer
// for forward compatibility.
type FavoriteServiceServer interface {
	Favorite(context.Context, *FavoriteReq) (*FavoriteRes, error)
	RemoveFavorite(context.Context, *RemoveFavoriteReq) (*RemoveFavoriteRes, error)
	QueryFavoriteInfo(context.Context, *QueryFavoriteInfoReq) (*QueryFavoriteInfoRes, error)
	QueryFavoriteList(context.Context, *QueryFavoriteListReq) (*QueryFavoriteListRes, error)
	mustEmbedUnimplementedFavoriteServiceServer()
}

// UnimplementedFavoriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFavoriteServiceServer struct{}

func (UnimplementedFavoriteServiceServer) Favorite(context.Context, *FavoriteReq) (*FavoriteRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Favorite not implemented")
}
func (UnimplementedFavoriteServiceServer) RemoveFavorite(context.Context, *RemoveFavoriteReq) (*RemoveFavoriteRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFavorite not implemented")
}
func (UnimplementedFavoriteServiceServer) QueryFavoriteInfo(context.Context, *QueryFavoriteInfoReq) (*QueryFavoriteInfoRes, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryFavoriteInfo not implemented")
}
func (UnimplementedFavoriteServiceServer) QueryFavoriteList(context.Context, *QueryFavoriteListReq) (*QueryFavoriteListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryFavoriteList not implemented")
}
func (UnimplementedFavoriteServiceServer) mustEmbedUnimplementedFavoriteServiceServer() {}
func (UnimplementedFavoriteServiceServer) testEmbeddedByValue()                         {}

// UnsafeFavoriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavoriteServiceServer will
// result in compilation errors.
type UnsafeFavoriteServiceServer interface {
	mustEmbedUnimplementedFavoriteServiceServer()
}

func RegisterFavoriteServiceServer(s grpc.ServiceRegistrar, srv FavoriteServiceServer) {
	// If the following call panics, it indicates UnimplementedFavoriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FavoriteService_ServiceDesc, srv)
}

func _FavoriteService_Favorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).Favorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_Favorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).Favorite(ctx, req.(*FavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_RemoveFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).RemoveFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_RemoveFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).RemoveFavorite(ctx, req.(*RemoveFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_QueryFavoriteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFavoriteInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).QueryFavoriteInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_QueryFavoriteInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).QueryFavoriteInfo(ctx, req.(*QueryFavoriteInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_QueryFavoriteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFavoriteListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).QueryFavoriteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_QueryFavoriteList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).QueryFavoriteList(ctx, req.(*QueryFavoriteListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FavoriteService_ServiceDesc is the grpc.ServiceDesc for FavoriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FavoriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.FavoriteService",
	HandlerType: (*FavoriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Favorite",
			Handler:    _FavoriteService_Favorite_Handler,
		},
		{
			MethodName: "RemoveFavorite",
			Handler:    _FavoriteService_RemoveFavorite_Handler,
		},
		{
			MethodName: "QueryFavoriteInfo",
			Handler:    _FavoriteService_QueryFavoriteInfo_Handler,
		},
		{
			MethodName: "QueryFavoriteList",
			Handler:    _FavoriteService_QueryFavoriteList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}

const (
	CommentService_Comment_FullMethodName            = "/interaction.CommentService/Comment"
	CommentService_DeleteComment_FullMethodName      = "/interaction.CommentService/DeleteComment"
	CommentService_QueryCommentList_FullMethodName   = "/interaction.CommentService/QueryCommentList"
	CommentService_QueryReplyList_FullMethodName     = "/interaction.CommentService/QueryReplyList"
	CommentService_BatchGetComments_FullMethodName   = "/interaction.CommentService/BatchGetComments"
	CommentService_RefillCommentCache_FullMethodName = "/interaction.CommentService/RefillCommentCache"
)

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentServiceClient interface {
	Comment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentRes, error)
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentRes, error)
	QueryCommentList(ctx context.Context, in *QueryCommentListReq, opts ...grpc.CallOption) (*QueryCommentListRes, error)
	QueryReplyList(ctx context.Context, in *QueryReplyListReq, opts ...grpc.CallOption) (*QueryReplyListRes, error)
	BatchGetComments(ctx context.Context, in *BatchGetCommentsReq, opts ...grpc.CallOption) (*BatchGetCommentsRes, error)
	RefillCommentCache(ctx context.Context, in *RefillCommentCacheReq, opts ...grpc.CallOption) (*RefillCommentCacheRes, error)
}

type commentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentServiceClient(cc grpc.ClientConnInterface) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) Comment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentRes)
	err := c.cc.Invoke(ctx, CommentService_Comment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentRes)
	err := c.cc.Invoke(ctx, CommentService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) QueryCommentList(ctx context.Context, in *QueryCommentListReq, opts ...grpc.CallOption) (*QueryCommentListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryCommentListRes)
	err := c.cc.Invoke(ctx, CommentService_QueryCommentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) QueryReplyList(ctx context.Context, in *QueryReplyListReq, opts ...grpc.CallOption) (*QueryReplyListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReplyListRes)
	err := c.cc.Invoke(ctx, CommentService_QueryReplyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) BatchGetComments(ctx context.Context, in *BatchGetCommentsReq, opts ...grpc.CallOption) (*BatchGetCommentsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetCommentsRes)
	err := c.cc.Invoke(ctx, CommentService_BatchGetComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) RefillCommentCache(ctx context.Context, in *RefillCommentCacheReq, opts ...grpc.CallOption) (*RefillCommentCacheRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefillCommentCacheRes)
	err := c.cc.Invoke(ctx, CommentService_RefillCommentCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
// All implementations must embed UnimplementedCommentServiceServer
// for forward compatibility.
type CommentServiceServer interface {
	Comment(context.Context, *CommentReq) (*CommentRes, error)
	DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentRes, error)
	QueryCommentList(context.Context, *QueryCommentListReq) (*QueryCommentListRes, error)
	QueryReplyList(context.Context, *QueryReplyListReq) (*QueryReplyListRes, error)
	BatchGetComments(context.Context, *BatchGetCommentsReq) (*BatchGetCommentsRes, error)
	RefillCommentCache(context.Context, *RefillCommentCacheReq) (*RefillCommentCacheRes, error)
	mustEmbedUnimplementedCommentServiceServer()
}

// UnimplementedCommentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentServiceServer struct{}

func (UnimplementedCommentServiceServer) Comment(context.Context, *CommentReq) (*CommentRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Comment not implemented")
}
func (UnimplementedCommentServiceServer) DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCommentServiceServer) QueryCommentList(context.Context, *QueryCommentListReq) (*QueryCommentListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryCommentList not implemented")
}
func (UnimplementedCommentServiceServer) QueryReplyList(context.Context, *QueryReplyListReq) (*QueryReplyListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryReplyList not implemented")
}
func (UnimplementedCommentServiceServer) BatchGetComments(context.Context, *BatchGetCommentsReq) (*BatchGetCommentsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetComments not implemented")
}
func (UnimplementedCommentServiceServer) RefillCommentCache(context.Context, *RefillCommentCacheReq) (*RefillCommentCacheRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RefillCommentCache not implemented")
}
func (UnimplementedCommentServiceServer) mustEmbedUnimplementedCommentServiceServer() {}
func (UnimplementedCommentServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServiceServer will
// result in compilation errors.
type UnsafeCommentServiceServer interface {
	mustEmbedUnimplementedCommentServiceServer()
}

func RegisterCommentServiceServer(s grpc.ServiceRegistrar, srv CommentServiceServer) {
	// If the following call panics, it indicates UnimplementedCommentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommentService_ServiceDesc, srv)
}

func _CommentService_Comment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).Comment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_Comment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).Comment(ctx, req.(*CommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).DeleteComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_QueryCommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).QueryCommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_QueryCommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).QueryCommentList(ctx, req.(*QueryCommentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_QueryReplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReplyListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).QueryReplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_QueryReplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).QueryReplyList(ctx, req.(*QueryReplyListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_BatchGetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).BatchGetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_BatchGetComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).BatchGetComments(ctx, req.(*BatchGetCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_RefillCommentCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefillCommentCacheReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).RefillCommentCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_RefillCommentCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).RefillCommentCache(ctx, req.(*RefillCommentCacheReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentService_ServiceDesc is the grpc.ServiceDesc for CommentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Comment",
			Handler:    _CommentService_Comment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _CommentService_DeleteComment_Handler,
		},
		{
			MethodName: "QueryCommentList",
			Handler:    _CommentService_QueryCommentList_Handler,
		},
		{
			MethodName: "QueryReplyList",
			Handler:    _CommentService_QueryReplyList_Handler,
		},
		{
			MethodName: "BatchGetComments",
			Handler:    _CommentService_BatchGetComments_Handler,
		},
		{
			MethodName: "RefillCommentCache",
			Handler:    _CommentService_RefillCommentCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}

const (
	FollowService_FollowUser_FullMethodName          = "/interaction.FollowService/FollowUser"
	FollowService_UnfollowUser_FullMethodName        = "/interaction.FollowService/UnfollowUser"
	FollowService_ListFollowees_FullMethodName       = "/interaction.FollowService/ListFollowees"
	FollowService_ListFollowers_FullMethodName       = "/interaction.FollowService/ListFollowers"
	FollowService_BatchQueryFollowing_FullMethodName = "/interaction.FollowService/BatchQueryFollowing"
	FollowService_GetFollowSummary_FullMethodName    = "/interaction.FollowService/GetFollowSummary"
)

// FollowServiceClient is the client API for FollowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FollowServiceClient interface {
	FollowUser(ctx context.Context, in *FollowUserReq, opts ...grpc.CallOption) (*FollowUserRes, error)
	UnfollowUser(ctx context.Context, in *UnfollowUserReq, opts ...grpc.CallOption) (*UnfollowUserRes, error)
	ListFollowees(ctx context.Context, in *ListFolloweesReq, opts ...grpc.CallOption) (*ListFolloweesRes, error)
	ListFollowers(ctx context.Context, in *ListFollowersReq, opts ...grpc.CallOption) (*ListFollowersRes, error)
	BatchQueryFollowing(ctx context.Context, in *BatchQueryFollowingReq, opts ...grpc.CallOption) (*BatchQueryFollowingRes, error)
	GetFollowSummary(ctx context.Context, in *GetFollowSummaryReq, opts ...grpc.CallOption) (*GetFollowSummaryRes, error)
}

type followServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowServiceClient(cc grpc.ClientConnInterface) FollowServiceClient {
	return &followServiceClient{cc}
}

func (c *followServiceClient) FollowUser(ctx context.Context, in *FollowUserReq, opts ...grpc.CallOption) (*FollowUserRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowUserRes)
	err := c.cc.Invoke(ctx, FollowService_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) UnfollowUser(ctx context.Context, in *UnfollowUserReq, opts ...grpc.CallOption) (*UnfollowUserRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowUserRes)
	err := c.cc.Invoke(ctx, FollowService_UnfollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) ListFollowees(ctx context.Context, in *ListFolloweesReq, opts ...grpc.CallOption) (*ListFolloweesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFolloweesRes)
	err := c.cc.Invoke(ctx, FollowService_ListFollowees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) ListFollowers(ctx context.Context, in *ListFollowersReq, opts ...grpc.CallOption) (*ListFollowersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFollowersRes)
	err := c.cc.Invoke(ctx, FollowService_ListFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) BatchQueryFollowing(ctx context.Context, in *BatchQueryFollowingReq, opts ...grpc.CallOption) (*BatchQueryFollowingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchQueryFollowingRes)
	err := c.cc.Invoke(ctx, FollowService_BatchQueryFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) GetFollowSummary(ctx context.Context, in *GetFollowSummaryReq, opts ...grpc.CallOption) (*GetFollowSummaryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowSummaryRes)
	err := c.cc.Invoke(ctx, FollowService_GetFollowSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowServiceServer is the server API for FollowService service.
// All implementations must embed UnimplementedFollowServiceServer
// for forward compatibility.
type FollowServiceServer interface {
	FollowUser(context.Context, *FollowUserReq) (*FollowUserRes, error)
	UnfollowUser(context.Context, *UnfollowUserReq) (*UnfollowUserRes, error)
	ListFollowees(context.Context, *ListFolloweesReq) (*ListFolloweesRes, error)
	ListFollowers(context.Context, *ListFollowersReq) (*ListFollowersRes, error)
	BatchQueryFollowing(context.Context, *BatchQueryFollowingReq) (*BatchQueryFollowingRes, error)
	GetFollowSummary(context.Context, *GetFollowSummaryReq) (*GetFollowSummaryRes, error)
	mustEmbedUnimplementedFollowServiceServer()
}

// UnimplementedFollowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowServiceServer struct{}

func (UnimplementedFollowServiceServer) FollowUser(context.Context, *FollowUserReq) (*FollowUserRes, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedFollowServiceServer) UnfollowUser(context.Context, *UnfollowUserReq) (*UnfollowUserRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfollowUser not implemented")
}
func (UnimplementedFollowServiceServer) ListFollowees(context.Context, *ListFolloweesReq) (*ListFolloweesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowees not implemented")
}
func (UnimplementedFollowServiceServer) ListFollowers(context.Context, *ListFollowersReq) (*ListFollowersRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowers not implemented")
}
func (UnimplementedFollowServiceServer) BatchQueryFollowing(context.Context, *BatchQueryFollowingReq) (*BatchQueryFollowingRes, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchQueryFollowing not implemented")
}
func (UnimplementedFollowServiceServer) GetFollowSummary(context.Context, *GetFollowSummaryReq) (*GetFollowSummaryRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowSummary not implemented")
}
func (UnimplementedFollowServiceServer) mustEmbedUnimplementedFollowServiceServer() {}
func (UnimplementedFollowServiceServer) testEmbeddedByValue()                       {}

// UnsafeFollowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowServiceServer will
// result in compilation errors.
type UnsafeFollowServiceServer interface {
	mustEmbedUnimplementedFollowServiceServer()
}

func RegisterFollowServiceServer(s grpc.ServiceRegistrar, srv FollowServiceServer) {
	// If the following call panics, it indicates UnimplementedFollowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowService_ServiceDesc, srv)
}

func _FollowService_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).FollowUser(ctx, req.(*FollowUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_UnfollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).UnfollowUser(ctx, req.(*UnfollowUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_ListFollowees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFolloweesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).ListFollowees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_ListFollowees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).ListFollowees(ctx, req.(*ListFolloweesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_ListFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).ListFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_ListFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).ListFollowers(ctx, req.(*ListFollowersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_BatchQueryFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchQueryFollowingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).BatchQueryFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_BatchQueryFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).BatchQueryFollowing(ctx, req.(*BatchQueryFollowingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_GetFollowSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).GetFollowSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_GetFollowSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).GetFollowSummary(ctx, req.(*GetFollowSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowService_ServiceDesc is the grpc.ServiceDesc for FollowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.FollowService",
	HandlerType: (*FollowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowUser",
			Handler:    _FollowService_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _FollowService_UnfollowUser_Handler,
		},
		{
			MethodName: "ListFollowees",
			Handler:    _FollowService_ListFollowees_Handler,
		},
		{
			MethodName: "ListFollowers",
			Handler:    _FollowService_ListFollowers_Handler,
		},
		{
			MethodName: "BatchQueryFollowing",
			Handler:    _FollowService_BatchQueryFollowing_Handler,
		},
		{
			MethodName: "GetFollowSummary",
			Handler:    _FollowService_GetFollowSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}
