// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: app/rpc/content/proto/content.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNKNOWN ContentType = 0
	ContentType_CONTENT_TYPE_ARTICLE ContentType = 10
	ContentType_CONTENT_TYPE_VIDEO   ContentType = 20
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0:  "CONTENT_TYPE_UNKNOWN",
		10: "CONTENT_TYPE_ARTICLE",
		20: "CONTENT_TYPE_VIDEO",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNKNOWN": 0,
		"CONTENT_TYPE_ARTICLE": 10,
		"CONTENT_TYPE_VIDEO":   20,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_content_proto_content_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_app_rpc_content_proto_content_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_content_proto_content_proto_rawDescGZIP(), []int{0}
}

type ContentStatus int32

const (
	ContentStatus_CONTENT_STATUS_UNKNOWN    ContentStatus = 0
	ContentStatus_CONTENT_STATUS_DRAFT      ContentStatus = 10
	ContentStatus_CONTENT_STATUS_PROCESSING ContentStatus = 20
	ContentStatus_CONTENT_STATUS_PUBLISHED  ContentStatus = 30
	ContentStatus_CONTENT_STATUS_FAILED     ContentStatus = 40
)

// Enum value maps for ContentStatus.
var (
	ContentStatus_name = map[int32]string{
		0:  "CONTENT_STATUS_UNKNOWN",
		10: "CONTENT_STATUS_DRAFT",
		20: "CONTENT_STATUS_PROCESSING",
		30: "CONTENT_STATUS_PUBLISHED",
		40: "CONTENT_STATUS_FAILED",
	}
	ContentStatus_value = map[string]int32{
		"CONTENT_STATUS_UNKNOWN":    0,
		"CONTENT_STATUS_DRAFT":      10,
		"CONTENT_STATUS_PROCESSING": 20,
		"CONTENT_STATUS_PUBLISHED":  30,
		"CONTENT_STATUS_FAILED":     40,
	}
)

func (x ContentStatus) Enum() *ContentStatus {
	p := new(ContentStatus)
	*p = x
	return p
}

func (x ContentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_content_proto_content_proto_enumTypes[1].Descriptor()
}

func (ContentStatus) Type() protoreflect.EnumType {
	return &file_app_rpc_content_proto_content_proto_enumTypes[1]
}

func (x ContentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentStatus.Descriptor instead.
func (ContentStatus) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_content_proto_content_proto_rawDescGZIP(), []int{1}
}

type Visibility int32

const (
	Visibility_VISIBILITY_UNKNOWN Visibility = 0
	Visibility_VISIBILITY_PUBLIC  Visibility = 10
	Visibility_VISIBILITY_PRIVATE Visibility = 20
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0:  "VISIBILITY_UNKNOWN",
		10: "VISIBILITY_PUBLIC",
		20: "VISIBILITY_PRIVATE",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNKNOWN": 0,
		"VISIBILITY_PUBLIC":  10,
		"VISIBILITY_PRIVATE": 20,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_content_proto_content_proto_enumTypes[2].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_app_rpc_content_proto_content_proto_enumTypes[2]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_content_proto_content_proto_rawDescGZIP(), []int{2}
}

type ArticlePublishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Visibility    Visibility             `protobuf:"varint,6,opt,name=visibility,proto3,enum=content.Visibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticlePublishReq) Reset() {
	*x = ArticlePublishReq{}
	mi := &file_app_rpc_content_proto_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlePublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlePublishReq) ProtoMessage() {}

func (x *ArticlePublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_content_proto_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlePublishReq.ProtoReflect.Descriptor instead.
func (*ArticlePublishReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_content_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *ArticlePublishReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ArticlePublishReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticlePublishReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ArticlePublishReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ArticlePublishReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticlePublishReq) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNKNOWN
}

type ArticlePublishRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticlePublishRes) Reset() {
	*x = ArticlePublishRes{}
	mi := &file_app_rpc_content_proto_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlePublishRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlePublishRes) ProtoMessage() {}

func (x *ArticlePublishRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_content_proto_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlePublishRes.ProtoReflect.Descriptor instead.
func (*ArticlePublishRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_content_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *ArticlePublishRes) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type VideoPublishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OriginUrl     string                 `protobuf:"bytes,4,opt,name=origin_url,json=originUrl,proto3" json:"origin_url,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Duration      int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Visibility    Visibility             `protobuf:"varint,7,opt,name=visibility,proto3,enum=content.Visibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoPublishReq) Reset() {
	*x = VideoPublishReq{}
	mi := &file_app_rpc_content_proto_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPublishReq) ProtoMessage() {}

func (x *VideoPublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_content_proto_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPublishReq.ProtoReflect.Descriptor instead.
func (*VideoPublishReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_content_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *VideoPublishReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VideoPublishReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoPublishReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *VideoPublishReq) GetOriginUrl() string {
	if x != nil {
		return x.OriginUrl
	}
	return ""
}

func (x *VideoPublishReq) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoPublishReq) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoPublishReq) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNKNOWN
}

type VideoPublishRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoPublishRes) Reset() {
	*x = VideoPublishRes{}
	mi := &file_app_rpc_content_proto_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPublishRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPublishRes) ProtoMessage() {}

func (x *VideoPublishRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_content_proto_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPublishRes.ProtoReflect.Descriptor instead.
func (*VideoPublishRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_content_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *VideoPublishRes) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

var File_app_rpc_content_proto_content_proto protoreflect.FileDescriptor

const file_app_rpc_content_proto_content_proto_rawDesc = "" +
	"\n" +
	"#app/rpc/content/proto/content.proto\x12\acontent\"\xde\x01\n" +
	"\x11ArticlePublishReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x123\n" +
	"\n" +
	"visibility\x18\x06 \x01(\x0e2\x13.content.VisibilityR\n" +
	"visibilityB\x0e\n" +
	"\f_description\"2\n" +
	"\x11ArticlePublishRes\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\"\x84\x02\n" +
	"\x0fVideoPublishReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"origin_url\x18\x04 \x01(\tR\toriginUrl\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x123\n" +
	"\n" +
	"visibility\x18\a \x01(\x0e2\x13.content.VisibilityR\n" +
	"visibilityB\x0e\n" +
	"\f_description\"0\n" +
	"\x0fVideoPublishRes\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId*Y\n" +
	"\vContentType\x12\x18\n" +
	"\x14CONTENT_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14CONTENT_TYPE_ARTICLE\x10\n" +
	"\x12\x16\n" +
	"\x12CONTENT_TYPE_VIDEO\x10\x14*\x9d\x01\n" +
	"\rContentStatus\x12\x1a\n" +
	"\x16CONTENT_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14CONTENT_STATUS_DRAFT\x10\n" +
	"\x12\x1d\n" +
	"\x19CONTENT_STATUS_PROCESSING\x10\x14\x12\x1c\n" +
	"\x18CONTENT_STATUS_PUBLISHED\x10\x1e\x12\x19\n" +
	"\x15CONTENT_STATUS_FAILED\x10(*S\n" +
	"\n" +
	"Visibility\x12\x16\n" +
	"\x12VISIBILITY_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\n" +
	"\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x142\x9e\x01\n" +
	"\x0eContentService\x12H\n" +
	"\x0ePublishArticle\x12\x1a.content.ArticlePublishReq\x1a\x1a.content.ArticlePublishRes\x12B\n" +
	"\fPublishVideo\x12\x18.content.VideoPublishReq\x1a\x18.content.VideoPublishResB\vZ\t./contentb\x06proto3"

var (
	file_app_rpc_content_proto_content_proto_rawDescOnce sync.Once
	file_app_rpc_content_proto_content_proto_rawDescData []byte
)

func file_app_rpc_content_proto_content_proto_rawDescGZIP() []byte {
	file_app_rpc_content_proto_content_proto_rawDescOnce.Do(func() {
		file_app_rpc_content_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_rpc_content_proto_content_proto_rawDesc), len(file_app_rpc_content_proto_content_proto_rawDesc)))
	})
	return file_app_rpc_content_proto_content_proto_rawDescData
}

var file_app_rpc_content_proto_content_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_app_rpc_content_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_rpc_content_proto_content_proto_goTypes = []any{
	(ContentType)(0),          // 0: content.ContentType
	(ContentStatus)(0),        // 1: content.ContentStatus
	(Visibility)(0),           // 2: content.Visibility
	(*ArticlePublishReq)(nil), // 3: content.ArticlePublishReq
	(*ArticlePublishRes)(nil), // 4: content.ArticlePublishRes
	(*VideoPublishReq)(nil),   // 5: content.VideoPublishReq
	(*VideoPublishRes)(nil),   // 6: content.VideoPublishRes
}
var file_app_rpc_content_proto_content_proto_depIdxs = []int32{
	2, // 0: content.ArticlePublishReq.visibility:type_name -> content.Visibility
	2, // 1: content.VideoPublishReq.visibility:type_name -> content.Visibility
	3, // 2: content.ContentService.PublishArticle:input_type -> content.ArticlePublishReq
	5, // 3: content.ContentService.PublishVideo:input_type -> content.VideoPublishReq
	4, // 4: content.ContentService.PublishArticle:output_type -> content.ArticlePublishRes
	6, // 5: content.ContentService.PublishVideo:output_type -> content.VideoPublishRes
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_rpc_content_proto_content_proto_init() }
func file_app_rpc_content_proto_content_proto_init() {
	if File_app_rpc_content_proto_content_proto != nil {
		return
	}
	file_app_rpc_content_proto_content_proto_msgTypes[0].OneofWrappers = []any{}
	file_app_rpc_content_proto_content_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_rpc_content_proto_content_proto_rawDesc), len(file_app_rpc_content_proto_content_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_rpc_content_proto_content_proto_goTypes,
		DependencyIndexes: file_app_rpc_content_proto_content_proto_depIdxs,
		EnumInfos:         file_app_rpc_content_proto_content_proto_enumTypes,
		MessageInfos:      file_app_rpc_content_proto_content_proto_msgTypes,
	}.Build()
	File_app_rpc_content_proto_content_proto = out.File
	file_app_rpc_content_proto_content_proto_goTypes = nil
	file_app_rpc_content_proto_content_proto_depIdxs = nil
}
