// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BatchQueryLikeInfoReq struct {
	LikeInfos []QueryLikeInfoReq `json:"like_infos" validate:"required"`
}

type BatchQueryLikeInfoRes struct {
	LikeInfos []QueryLikeInfoRes `json:"like_infos"`
}

type CommentItem struct {
	CommentId     int64  `json:"comment_id"`
	ContentId     int64  `json:"content_id"`
	UserId        int64  `json:"user_id"`
	ReplyToUserId int64  `json:"reply_to_user_id"`
	ParentId      int64  `json:"parent_id"`
	RootId        int64  `json:"root_id"`
	Comment       string `json:"comment"`
	CreatedAt     int64  `json:"created_at"`
	Status        int32  `json:"status"`
	UserName      string `json:"user_name"`
	UserAvatar    string `json:"user_avatar"`
	ReplyCount    int64  `json:"reply_count"`
}

type CommentReq struct {
	ContentId     *int64  `json:"content_id,string,optional" validate:"required"`
	Scene         *string `json:"scene,optional" validate:"required"`
	Comment       *string `json:"comment,optional" validate:"required,max=255"`
	ParentId      *int64  `json:"parent_id,string,optional"`
	RootId        *int64  `json:"root_id,string,optional"`
	ReplyToUserId *int64  `json:"reply_to_user_id,string,optional"`
	ContentUserId *int64  `json:"content_user_id,string,optional" validate:"required"`
}

type CommentRes struct {
	CommentId int64 `json:"comment_id,string"`
}

type ContentDetail struct {
	ContentId         int64  `json:"content_id,string"`
	ContentType       int32  `json:"content_type"`
	AuthorId          int64  `json:"author_id,string"`
	AuthorName        string `json:"author_name"`
	AuthorAvatar      string `json:"author_avatar"`
	Title             string `json:"title"`
	Description       string `json:"description"`
	CoverUrl          string `json:"cover_url"`
	ArticleContent    string `json:"article_content"`
	VideoUrl          string `json:"video_url"`
	VideoDuration     int32  `json:"video_duration"`
	PublishedAt       int64  `json:"published_at"`
	LikeCount         int64  `json:"like_count"`
	FavoriteCount     int64  `json:"favorite_count"`
	CommentCount      int64  `json:"comment_count"`
	IsLiked           bool   `json:"is_liked"`
	IsFavorited       bool   `json:"is_favorited"`
	IsFollowingAuthor bool   `json:"is_following_author"`
}

type ContentUploadsCredentialsReq struct {
	Scene    *string `json:"scene,optional" validate:"required"`
	FileExt  *string `json:"file_ext,optional" validate:"required"`
	FileSize *int64  `json:"file_size,optional" validate:"required,min=1,max=10737418240"`
	FileName *string `json:"file_name,optional" validate:"required"`
}

type ContentUploadsCredentialsRes struct {
	ObjectKey string      `json:"object_key"`
	FormData  OssFormData `json:"form_data"`
	ExpiredAt int64       `json:"expired_at"`
}

type DeleteCommentReq struct {
	CommentId *int64  `json:"comment_id,string,optional" validate:"required"`
	ContentId *int64  `json:"content_id,string,optional" validate:"required"`
	RootId    *int64  `json:"root_id,string,optional"`
	ParentId  *int64  `json:"parent_id,string,optional"`
	Scene     *string `json:"scene,optional"`
}

type DeleteCommentRes struct {
}

type DeleteContentReq struct {
	ContentId int64 `path:"content_id"`
}

type DeleteContentRes struct {
}

type FavoriteReq struct {
	ContentId     *int64  `json:"content_id,string,optional" validate:"required"`
	ContentUserId *int64  `json:"content_user_id,string,optional" validate:"required"`
	Scene         *string `json:"scene,optional" validate:"required"`
}

type FavoriteRes struct {
}

type FollowFeedItem struct {
	ContentId    int64  `json:"content_id,string"`
	ContentType  int32  `json:"content_type"`
	AuthorId     int64  `json:"author_id,string"`
	AuthorName   string `json:"author_name"`
	AuthorAvatar string `json:"author_avatar"`
	Title        string `json:"title"`
	CoverUrl     string `json:"cover_url"`
	PublishedAt  int64  `json:"published_at"`
	IsLiked      bool   `json:"is_liked"`
	LikeCount    int64  `json:"like_count"`
}

type FollowFeedReq struct {
	Cursor   *string `json:"cursor,optional" validate:"required"`
	PageSize *uint32 `json:"page_size,optional" validate:"required,min=1,max=50"`
}

type FollowFeedRes struct {
	Items      []FollowFeedItem `json:"items"`
	NextCursor string           `json:"next_cursor"`
	HasMore    bool             `json:"has_more"`
}

type FollowUserReq struct {
	TargetUserId *int64 `json:"target_user_id,string,optional" validate:"required"`
}

type FollowUserRes struct {
	IsFollowed bool `json:"is_followed"`
}

type GetContentDetailReq struct {
	ContentId *int64 `json:"content_id,string,optional" validate:"required"`
}

type GetContentDetailRes struct {
	Detail ContentDetail `json:"detail"`
}

type GetMeRes struct {
	UserInfo              UserInfo `json:"user_info"`
	FolloweeCount         int64    `json:"followee_count"`
	FollowerCount         int64    `json:"follower_count"`
	LikeReceivedCount     int64    `json:"like_received_count"`
	FavoriteReceivedCount int64    `json:"favorite_received_count"`
}

type LikeReq struct {
	ContentId     *int64  `json:"content_id,string,optional" validate:"required"`
	ContentUserId *int64  `json:"content_user_id,string,optional" validate:"required"`
	Scene         *string `json:"scene,optional" validate:"required"`
}

type LikeRes struct {
}

type LoginReq struct {
	Mobile   *string `json:"mobile,optional" validate:"required"`
	Password *string `json:"password,optional" validate:"required"`
}

type LoginRes struct {
	UserId    int64  `json:"user_id"`
	Token     string `json:"token"`
	ExpiredAt int64  `json:"expired_at"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
}

type LogoutRes struct {
}

type OssFormData struct {
	Host             string `json:"host"`
	Policy           string `json:"policy"`
	Signature        string `json:"signature"`
	SecurityToken    string `json:"x-oss-security-token"`
	SignatureVersion string `json:"x-oss-signature-version"`
	Credential       string `json:"x-oss-credential"`
	Date             string `json:"x-oss-date"`
	Key              string `json:"key"`
}

type PageQueryReq struct {
	Page     uint32 `json:"page,default=1"`
	PageSize uint32 `json:"page_size,default=10"`
}

type PageQueryResp struct {
	Page     uint32 `json:"page"`
	PageSize uint32 `json:"page_size"`
	Total    uint32 `json:"total"`
}

type PublishArticleReq struct {
	Title       *string `json:"title,optional" validate:"required,min=1,max=100"`
	Description *string `json:"description,optional" validate:"min=1,max=255"`
	Cover       *string `json:"cover,optional" validate:"required,url"`
	Content     *string `json:"content,optional" validate:"required,min=1,max=1000000"`
	Visibility  *int32  `json:"visibility,optional" validate:"required"`
}

type PublishArticleRes struct {
	ContentId int64 `json:"content_id"`
}

type PublishVideoReq struct {
	Title       *string `json:"title,optional" validate:"required,min=1,max=100"`
	Description *string `json:"description,optional" validate:"min=1,max=500"`
	VideoUrl    *string `json:"video_url,optional" validate:"required,url"`
	CoverUrl    *string `json:"cover_url,optional" validate:"required,url"`
	Duration    *int32  `json:"duration,optional" validate:"min=1,max=7200"`
	Visibility  *int32  `json:"visibility,optional" validate:"required"`
}

type PublishVideoRes struct {
	ContentId int64 `json:"content_id"`
}

type QueryCommentListReq struct {
	ContentId *int64  `json:"content_id,string,optional" validate:"required"`
	Scene     *string `json:"scene,optional" validate:"required"`
	Cursor    *int64  `json:"cursor,optional" validate:"required,max=50"`
	PageSize  *uint32 `json:"page_size,optional" validate:"required,max=50"`
}

type QueryCommentListRes struct {
	Comments   []*CommentItem `json:"comments"`
	NextCursor int64          `json:"next_cursor"`
	HasMore    bool           `json:"has_more"`
}

type QueryFavoriteInfoReq struct {
	ContentId *int64  `json:"content_id,string,optional" validate:"required"`
	Scene     *string `json:"scene,optional" validate:"required"`
}

type QueryFavoriteInfoRes struct {
	FavoriteCount int64  `json:"favorite_count"`
	IsFavorite    bool   `json:"is_favorite"`
	ContentId     int64  `json:"content_id,string"`
	Scene         string `json:"scene"`
}

type QueryLikeInfoReq struct {
	ContentId *int64  `json:"content_id,string,optional" validate:"required"`
	Scene     *string `json:"scene,optional" validate:"required"`
}

type QueryLikeInfoRes struct {
	LikeCount int64  `json:"like_count"`
	IsLiked   bool   `json:"is_liked"`
	ContentId int64  `json:"content_id,string"`
	Scene     string `json:"scene"`
}

type QueryReplyCommentListReq struct {
	CommentId *int64  `json:"comment_id,string,optional" validate:"required"`
	Cursor    *int64  `json:"cursor,optional" validate:"required"`
	PageSize  *uint32 `json:"page_size,optional" validate:"required"`
}

type QueryReplyCommentListRes struct {
	Comments   []*CommentItem `json:"comments"`
	NextCursor int64          `json:"next_cursor"`
	HasMore    bool           `json:"has_more"`
}

type QueryUserProfileReq struct {
	UserId int64 `json:"user_id,optional" validate:"required"`
}

type QueryUserProfileRes struct {
	UserProfileInfo    UserProfileInfo    `json:"user_profile"`
	UserProfileCounts  UserProfileCounts  `json:"counts"`
	ViewerProfileState ViewerProfileState `json:"viewer"`
}

type RecommendFeedItem struct {
	ContentId    int64  `json:"content_id,string"`
	ContentType  int32  `json:"content_type"`
	AuthorId     int64  `json:"author_id,string"`
	AuthorName   string `json:"author_name"`
	AuthorAvatar string `json:"author_avatar"`
	Title        string `json:"title"`
	CoverUrl     string `json:"cover_url"`
	PublishedAt  int64  `json:"published_at"`
	IsLiked      bool   `json:"is_liked"`
	LikeCount    int64  `json:"like_count"`
}

type RecommendFeedReq struct {
	Cursor     *string `json:"cursor,optional" validate:"required"`
	PageSize   *uint32 `json:"page_size,optional" validate:"required,min=1,max=50"`
	SnapshotId *string `json:"snapshot_id,optional"`
}

type RecommendFeedRes struct {
	Items      []RecommendFeedItem `json:"items"`
	NextCursor string              `json:"next_cursor"`
	HasMore    bool                `json:"has_more"`
	SnapshotId string              `json:"snapshot_id"`
}

type RegisterReq struct {
	Mobile   *string `json:"mobile,optional" validate:"required,e164"`
	Password *string `json:"password,optional" validate:"required"`
	Nickname *string `json:"nickname,optional" validate:"max=64"`
	Avatar   *string `json:"avatar,optional" validate:"required"`
	Bio      *string `json:"bio,optional" validate:"max=255"`
	Gender   *int32  `json:"gender,optional" validate:"required,oneof=0 1 2"`
	Email    *string `json:"email,optional" validate:"required,email"`
	Birthday *int64  `json:"birthday,optional" validate:"required"`
}

type RegisterRes struct {
	UserId    int64  `json:"user_id"`
	Token     string `json:"token"`
	ExpiredAt int64  `json:"expired_at"`
}

type RemoveFavoriteReq struct {
	ContentId *int64  `json:"content_id,string,optional" validate:"required"`
	Scene     *string `json:"scene,optional" validate:"required"`
}

type RemoveFavoriteRes struct {
}

type UnFollowUserReq struct {
	TargetUserId *int64 `json:"target_user_id,string,optional" validate:"required"`
}

type UnFollowUserRes struct {
	IsFollowed bool `json:"is_followed"`
}

type UnlikeReq struct {
	ContentId *int64  `json:"content_id,string,optional" validate:"required"`
	Scene     *string `json:"scene,optional" validate:"required"`
}

type UnlikeRes struct {
}

type UploadAvatarRes struct {
	Url       string `json:"url"`
	ObjectKey string `json:"object_key"`
	Mime      string `json:"mime"`
	Size      int64  `json:"size"`
}

type UserFavoriteFeedItem struct {
	ContentId    int64  `json:"content_id,string"`
	ContentType  int32  `json:"content_type"`
	AuthorId     int64  `json:"author_id,string"`
	AuthorName   string `json:"author_name"`
	AuthorAvatar string `json:"author_avatar"`
	Title        string `json:"title"`
	CoverUrl     string `json:"cover_url"`
	PublishedAt  int64  `json:"published_at"`
	IsLiked      bool   `json:"is_liked"`
	LikeCount    int64  `json:"like_count"`
}

type UserFavoriteFeedReq struct {
	UserId   *int64  `json:"user_id,string,optional" validate:"required"`
	Cursor   *string `json:"cursor,optional" validate:"required"`
	PageSize *uint32 `json:"page_size,optional" validate:"required,min=1,max=50"`
}

type UserFavoriteFeedRes struct {
	Items      []UserFavoriteFeedItem `json:"items"`
	NextCursor string                 `json:"next_cursor"`
	HasMore    bool                   `json:"has_more"`
}

type UserInfo struct {
	UserId   int64  `json:"user_id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Bio      string `json:"bio"`
	Gender   int32  `json:"gender"`
	Status   int32  `json:"status"`
}

type UserProfileCounts struct {
	FolloweeCount         int64 `json:"followee_count"`
	FollowerCount         int64 `json:"follower_count"`
	LikeReceivedCount     int64 `json:"like_received_count"`
	FavoriteReceivedCount int64 `json:"favorite_received_count"`
	ContentCount          int64 `json:"content_count"`
}

type UserProfileInfo struct {
	UserId   int64  `json:"user_id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Bio      string `json:"bio"`
	Gender   int32  `json:"gender"`
}

type UserPublishFeedItem struct {
	ContentId    int64  `json:"content_id,string"`
	ContentType  int32  `json:"content_type"`
	AuthorId     int64  `json:"author_id,string"`
	AuthorName   string `json:"author_name"`
	AuthorAvatar string `json:"author_avatar"`
	Title        string `json:"title"`
	CoverUrl     string `json:"cover_url"`
	PublishedAt  int64  `json:"published_at"`
	IsLiked      bool   `json:"is_liked"`
	LikeCount    int64  `json:"like_count"`
}

type UserPublishFeedReq struct {
	ViewerId *int64  `json:"viewer_id,string,optional"`
	UserId   *int64  `json:"user_id,string,optional" validate:"required"`
	Cursor   *string `json:"cursor,optional" validate:"required"`
	PageSize *uint32 `json:"page_size,optional" validate:"required,min=1,max=50"`
}

type UserPublishFeedRes struct {
	Items      []UserPublishFeedItem `json:"items"`
	NextCursor string                `json:"next_cursor"`
	HasMore    bool                  `json:"has_more"`
}

type ViewerProfileState struct {
	IsFollowing bool `json:"is_following"`
}
