// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package likeservice

import (
	"context"

	"zfeed/app/rpc/interaction/interaction"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetCommentsReq   = interaction.BatchGetCommentsReq
	BatchGetCommentsRes   = interaction.BatchGetCommentsRes
	BatchQueryIsLikedReq  = interaction.BatchQueryIsLikedReq
	BatchQueryIsLikedRes  = interaction.BatchQueryIsLikedRes
	BatchQueryLikeInfoReq = interaction.BatchQueryLikeInfoReq
	BatchQueryLikeInfoRes = interaction.BatchQueryLikeInfoRes
	CommentItem           = interaction.CommentItem
	CommentReq            = interaction.CommentReq
	CommentRes            = interaction.CommentRes
	DeleteCommentReq      = interaction.DeleteCommentReq
	DeleteCommentRes      = interaction.DeleteCommentRes
	FavoriteItem          = interaction.FavoriteItem
	FavoriteReq           = interaction.FavoriteReq
	FavoriteRes           = interaction.FavoriteRes
	FollowUserReq         = interaction.FollowUserReq
	FollowUserRes         = interaction.FollowUserRes
	FollowerProfile       = interaction.FollowerProfile
	GetFollowSummaryReq   = interaction.GetFollowSummaryReq
	GetFollowSummaryRes   = interaction.GetFollowSummaryRes
	IsLikedInfo           = interaction.IsLikedInfo
	LikeInfo              = interaction.LikeInfo
	LikeReq               = interaction.LikeReq
	LikeRes               = interaction.LikeRes
	ListFolloweesReq      = interaction.ListFolloweesReq
	ListFolloweesRes      = interaction.ListFolloweesRes
	ListFollowersReq      = interaction.ListFollowersReq
	ListFollowersRes      = interaction.ListFollowersRes
	PageReq               = interaction.PageReq
	PageRes               = interaction.PageRes
	QueryCommentListReq   = interaction.QueryCommentListReq
	QueryCommentListRes   = interaction.QueryCommentListRes
	QueryFavoriteInfoReq  = interaction.QueryFavoriteInfoReq
	QueryFavoriteInfoRes  = interaction.QueryFavoriteInfoRes
	QueryFavoriteListReq  = interaction.QueryFavoriteListReq
	QueryFavoriteListRes  = interaction.QueryFavoriteListRes
	QueryLikeInfoReq      = interaction.QueryLikeInfoReq
	QueryLikeInfoRes      = interaction.QueryLikeInfoRes
	QueryReplyListReq     = interaction.QueryReplyListReq
	QueryReplyListRes     = interaction.QueryReplyListRes
	RefillCommentCacheReq = interaction.RefillCommentCacheReq
	RefillCommentCacheRes = interaction.RefillCommentCacheRes
	RemoveFavoriteReq     = interaction.RemoveFavoriteReq
	RemoveFavoriteRes     = interaction.RemoveFavoriteRes
	UnfollowUserReq       = interaction.UnfollowUserReq
	UnfollowUserRes       = interaction.UnfollowUserRes
	UnlikeReq             = interaction.UnlikeReq
	UnlikeRes             = interaction.UnlikeRes

	LikeService interface {
		Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeRes, error)
		Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeRes, error)
		QueryLikeInfo(ctx context.Context, in *QueryLikeInfoReq, opts ...grpc.CallOption) (*QueryLikeInfoRes, error)
		BatchQueryLikeInfo(ctx context.Context, in *BatchQueryLikeInfoReq, opts ...grpc.CallOption) (*BatchQueryLikeInfoRes, error)
		BatchQueryIsLiked(ctx context.Context, in *BatchQueryIsLikedReq, opts ...grpc.CallOption) (*BatchQueryIsLikedRes, error)
	}

	defaultLikeService struct {
		cli zrpc.Client
	}
)

func NewLikeService(cli zrpc.Client) LikeService {
	return &defaultLikeService{
		cli: cli,
	}
}

func (m *defaultLikeService) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeRes, error) {
	client := interaction.NewLikeServiceClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

func (m *defaultLikeService) Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeRes, error) {
	client := interaction.NewLikeServiceClient(m.cli.Conn())
	return client.Unlike(ctx, in, opts...)
}

func (m *defaultLikeService) QueryLikeInfo(ctx context.Context, in *QueryLikeInfoReq, opts ...grpc.CallOption) (*QueryLikeInfoRes, error) {
	client := interaction.NewLikeServiceClient(m.cli.Conn())
	return client.QueryLikeInfo(ctx, in, opts...)
}

func (m *defaultLikeService) BatchQueryLikeInfo(ctx context.Context, in *BatchQueryLikeInfoReq, opts ...grpc.CallOption) (*BatchQueryLikeInfoRes, error) {
	client := interaction.NewLikeServiceClient(m.cli.Conn())
	return client.BatchQueryLikeInfo(ctx, in, opts...)
}

func (m *defaultLikeService) BatchQueryIsLiked(ctx context.Context, in *BatchQueryIsLikedReq, opts ...grpc.CallOption) (*BatchQueryIsLikedRes, error) {
	client := interaction.NewLikeServiceClient(m.cli.Conn())
	return client.BatchQueryIsLiked(ctx, in, opts...)
}
