canal.instance.mysql.slaveId=1235

canal.instance.gtidon=false

canal.instance.master.address=mysql:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.tsdb.enable=true

canal.instance.dbUsername=zfeed
canal.instance.dbPassword=123456
canal.instance.connectionCharset=UTF-8

canal.instance.filter.regex=zfeed\\.(zfeed_content|zfeed_article|zfeed_video|zfeed_user)

canal.mq.topic=zfeed-search-canal
canal.mq.partition=0
