// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package server

import (
	"context"

	"zfeed/app/rpc/content/content"
	"zfeed/app/rpc/content/internal/logic"
	contentservicelogic "zfeed/app/rpc/content/internal/logic/contentservice"
	"zfeed/app/rpc/content/internal/svc"
)

type ContentServiceServer struct {
	svcCtx *svc.ServiceContext
	content.UnimplementedContentServiceServer
}

func NewContentServiceServer(svcCtx *svc.ServiceContext) *ContentServiceServer {
	return &ContentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ContentServiceServer) PublishArticle(ctx context.Context, in *content.ArticlePublishReq) (*content.ArticlePublishRes, error) {
	l := logic.NewPublishArticleLogic(ctx, s.svcCtx)
	return l.PublishArticle(in)
}

func (s *ContentServiceServer) PublishVideo(ctx context.Context, in *content.VideoPublishReq) (*content.VideoPublishRes, error) {
	l := logic.NewPublishVideoLogic(ctx, s.svcCtx)
	return l.PublishVideo(in)
}

func (s *ContentServiceServer) BackfillFollowInbox(ctx context.Context, in *content.BackfillFollowInboxReq) (*content.BackfillFollowInboxRes, error) {
	l := logic.NewBackfillFollowInboxLogic(ctx, s.svcCtx)
	return l.BackfillFollowInbox(in)
}

func (s *ContentServiceServer) GetUploadCredentials(ctx context.Context, in *content.GetUploadCredentialsReq) (*content.GetUploadCredentialsRes, error) {
	l := contentservicelogic.NewGetUploadCredentialsLogic(ctx, s.svcCtx)
	return l.GetUploadCredentials(in)
}

func (s *ContentServiceServer) GetContentDetail(ctx context.Context, in *content.GetContentDetailReq) (*content.GetContentDetailRes, error) {
	l := contentservicelogic.NewGetContentDetailLogic(ctx, s.svcCtx)
	return l.GetContentDetail(in)
}

func (s *ContentServiceServer) EditArticle(ctx context.Context, in *content.EditArticleReq) (*content.EditArticleRes, error) {
	l := contentservicelogic.NewEditArticleLogic(ctx, s.svcCtx)
	return l.EditArticle(in)
}

func (s *ContentServiceServer) EditVideo(ctx context.Context, in *content.EditVideoReq) (*content.EditVideoRes, error) {
	l := contentservicelogic.NewEditVideoLogic(ctx, s.svcCtx)
	return l.EditVideo(in)
}

func (s *ContentServiceServer) DeleteContent(ctx context.Context, in *content.DeleteContentReq) (*content.DeleteContentRes, error) {
	l := contentservicelogic.NewDeleteContentLogic(ctx, s.svcCtx)
	return l.DeleteContent(in)
}
