// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package server

import (
	"context"

	"zfeed/app/rpc/content/content"
	"zfeed/app/rpc/content/internal/logic"
	"zfeed/app/rpc/content/internal/svc"
)

type ContentServiceServer struct {
	svcCtx *svc.ServiceContext
	content.UnimplementedContentServiceServer
}

func NewContentServiceServer(svcCtx *svc.ServiceContext) *ContentServiceServer {
	return &ContentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ContentServiceServer) PublishArticle(ctx context.Context, in *content.ArticlePublishReq) (*content.ArticlePublishRes, error) {
	l := logic.NewPublishArticleLogic(ctx, s.svcCtx)
	return l.PublishArticle(in)
}

func (s *ContentServiceServer) PublishVideo(ctx context.Context, in *content.VideoPublishReq) (*content.VideoPublishRes, error) {
	l := logic.NewPublishVideoLogic(ctx, s.svcCtx)
	return l.PublishVideo(in)
}
