// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package contentservice

import (
	"context"

	"zfeed/app/rpc/content/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticlePublishReq       = content.ArticlePublishReq
	ArticlePublishRes       = content.ArticlePublishRes
	BackfillFollowInboxReq  = content.BackfillFollowInboxReq
	BackfillFollowInboxRes  = content.BackfillFollowInboxRes
	ContentDetail           = content.ContentDetail
	ContentItem             = content.ContentItem
	DeleteContentReq        = content.DeleteContentReq
	DeleteContentRes        = content.DeleteContentRes
	EditArticleReq          = content.EditArticleReq
	EditArticleRes          = content.EditArticleRes
	EditVideoReq            = content.EditVideoReq
	EditVideoRes            = content.EditVideoRes
	FollowFeedItem          = content.FollowFeedItem
	FollowFeedReq           = content.FollowFeedReq
	FollowFeedRes           = content.FollowFeedRes
	GetContentDetailReq     = content.GetContentDetailReq
	GetContentDetailRes     = content.GetContentDetailRes
	GetUploadCredentialsReq = content.GetUploadCredentialsReq
	GetUploadCredentialsRes = content.GetUploadCredentialsRes
	OssFormData             = content.OssFormData
	RecommendFeedReq        = content.RecommendFeedReq
	RecommendFeedRes        = content.RecommendFeedRes
	UserFavoriteFeedReq     = content.UserFavoriteFeedReq
	UserFavoriteFeedRes     = content.UserFavoriteFeedRes
	UserPublishFeedReq      = content.UserPublishFeedReq
	UserPublishFeedRes      = content.UserPublishFeedRes
	VideoPublishReq         = content.VideoPublishReq
	VideoPublishRes         = content.VideoPublishRes

	ContentService interface {
		PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error)
		PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error)
		BackfillFollowInbox(ctx context.Context, in *BackfillFollowInboxReq, opts ...grpc.CallOption) (*BackfillFollowInboxRes, error)
		GetUploadCredentials(ctx context.Context, in *GetUploadCredentialsReq, opts ...grpc.CallOption) (*GetUploadCredentialsRes, error)
		GetContentDetail(ctx context.Context, in *GetContentDetailReq, opts ...grpc.CallOption) (*GetContentDetailRes, error)
		EditArticle(ctx context.Context, in *EditArticleReq, opts ...grpc.CallOption) (*EditArticleRes, error)
		EditVideo(ctx context.Context, in *EditVideoReq, opts ...grpc.CallOption) (*EditVideoRes, error)
		DeleteContent(ctx context.Context, in *DeleteContentReq, opts ...grpc.CallOption) (*DeleteContentRes, error)
	}

	defaultContentService struct {
		cli zrpc.Client
	}
)

func NewContentService(cli zrpc.Client) ContentService {
	return &defaultContentService{
		cli: cli,
	}
}

func (m *defaultContentService) PublishArticle(ctx context.Context, in *ArticlePublishReq, opts ...grpc.CallOption) (*ArticlePublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishArticle(ctx, in, opts...)
}

func (m *defaultContentService) PublishVideo(ctx context.Context, in *VideoPublishReq, opts ...grpc.CallOption) (*VideoPublishRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

func (m *defaultContentService) BackfillFollowInbox(ctx context.Context, in *BackfillFollowInboxReq, opts ...grpc.CallOption) (*BackfillFollowInboxRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.BackfillFollowInbox(ctx, in, opts...)
}

func (m *defaultContentService) GetUploadCredentials(ctx context.Context, in *GetUploadCredentialsReq, opts ...grpc.CallOption) (*GetUploadCredentialsRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.GetUploadCredentials(ctx, in, opts...)
}

func (m *defaultContentService) GetContentDetail(ctx context.Context, in *GetContentDetailReq, opts ...grpc.CallOption) (*GetContentDetailRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.GetContentDetail(ctx, in, opts...)
}

func (m *defaultContentService) EditArticle(ctx context.Context, in *EditArticleReq, opts ...grpc.CallOption) (*EditArticleRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.EditArticle(ctx, in, opts...)
}

func (m *defaultContentService) EditVideo(ctx context.Context, in *EditVideoReq, opts ...grpc.CallOption) (*EditVideoRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.EditVideo(ctx, in, opts...)
}

func (m *defaultContentService) DeleteContent(ctx context.Context, in *DeleteContentReq, opts ...grpc.CallOption) (*DeleteContentRes, error) {
	client := content.NewContentServiceClient(m.cli.Conn())
	return client.DeleteContent(ctx, in, opts...)
}
