// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: search.proto

package searchservice

import (
	"context"

	"zfeed/app/rpc/search/search"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SearchUsersReq    = search.SearchUsersReq
	SearchUsersRes    = search.SearchUsersRes
	SearchUserItem    = search.SearchUserItem
	SearchContentsReq = search.SearchContentsReq
	SearchContentsRes = search.SearchContentsRes
	SearchContentItem = search.SearchContentItem

	SearchService interface {
		SearchUsers(ctx context.Context, in *SearchUsersReq, opts ...grpc.CallOption) (*SearchUsersRes, error)
		SearchContents(ctx context.Context, in *SearchContentsReq, opts ...grpc.CallOption) (*SearchContentsRes, error)
	}

	defaultSearchService struct {
		cli zrpc.Client
	}
)

func NewSearchService(cli zrpc.Client) SearchService {
	return &defaultSearchService{
		cli: cli,
	}
}

func (m *defaultSearchService) SearchUsers(ctx context.Context, in *SearchUsersReq, opts ...grpc.CallOption) (*SearchUsersRes, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.SearchUsers(ctx, in, opts...)
}

func (m *defaultSearchService) SearchContents(ctx context.Context, in *SearchContentsReq, opts ...grpc.CallOption) (*SearchContentsRes, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.SearchContents(ctx, in, opts...)
}
