// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: count.proto

package server

import (
	"context"

	"zfeed/app/rpc/count/count"
	"zfeed/app/rpc/count/internal/logic"
	"zfeed/app/rpc/count/internal/svc"
)

type CounterServiceServer struct {
	svcCtx *svc.ServiceContext
	count.UnimplementedCounterServiceServer
}

func NewCounterServiceServer(svcCtx *svc.ServiceContext) *CounterServiceServer {
	return &CounterServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CounterServiceServer) GetCount(ctx context.Context, in *count.GetCountReq) (*count.GetCountRes, error) {
	l := logic.NewGetCountLogic(ctx, s.svcCtx)
	return l.GetCount(in)
}

func (s *CounterServiceServer) BatchGetCount(ctx context.Context, in *count.BatchGetCountReq) (*count.BatchGetCountRes, error) {
	l := logic.NewBatchGetCountLogic(ctx, s.svcCtx)
	return l.BatchGetCount(in)
}

func (s *CounterServiceServer) Inc(ctx context.Context, in *count.IncReq) (*count.IncRes, error) {
	l := logic.NewIncLogic(ctx, s.svcCtx)
	return l.Inc(in)
}

func (s *CounterServiceServer) Dec(ctx context.Context, in *count.DecReq) (*count.DecRes, error) {
	l := logic.NewDecLogic(ctx, s.svcCtx)
	return l.Dec(in)
}

func (s *CounterServiceServer) GetUserProfileCounts(ctx context.Context, in *count.GetUserProfileCountsReq) (*count.GetUserProfileCountsRes, error) {
	l := logic.NewGetUserProfileCountsLogic(ctx, s.svcCtx)
	return l.GetUserProfileCounts(in)
}
