// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: app/rpc/count/proto/count.proto

package count

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BizType 计数业务类型
type BizType int32

const (
	BizType_BIZ_TYPE_UNKNOWN BizType = 0
	BizType_LIKE             BizType = 10
	BizType_FAVORITE         BizType = 20
	BizType_COMMENT          BizType = 30
	BizType_FOLLOWED         BizType = 40
	BizType_FOLLOWING        BizType = 41
)

// Enum value maps for BizType.
var (
	BizType_name = map[int32]string{
		0:  "BIZ_TYPE_UNKNOWN",
		10: "LIKE",
		20: "FAVORITE",
		30: "COMMENT",
		40: "FOLLOWED",
		41: "FOLLOWING",
	}
	BizType_value = map[string]int32{
		"BIZ_TYPE_UNKNOWN": 0,
		"LIKE":             10,
		"FAVORITE":         20,
		"COMMENT":          30,
		"FOLLOWED":         40,
		"FOLLOWING":        41,
	}
)

func (x BizType) Enum() *BizType {
	p := new(BizType)
	*p = x
	return p
}

func (x BizType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BizType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_count_proto_count_proto_enumTypes[0].Descriptor()
}

func (BizType) Type() protoreflect.EnumType {
	return &file_app_rpc_count_proto_count_proto_enumTypes[0]
}

func (x BizType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BizType.Descriptor instead.
func (BizType) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{0}
}

// TargetType 计数对象类型
type TargetType int32

const (
	TargetType_TARGET_TYPE_UNKNOWN TargetType = 0
	TargetType_CONTENT             TargetType = 10
	TargetType_USER                TargetType = 20
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0:  "TARGET_TYPE_UNKNOWN",
		10: "CONTENT",
		20: "USER",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNKNOWN": 0,
		"CONTENT":             10,
		"USER":                20,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_count_proto_count_proto_enumTypes[1].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_app_rpc_count_proto_count_proto_enumTypes[1]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{1}
}

// GetCountReq 查询单个计数
type GetCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizType       BizType                `protobuf:"varint,1,opt,name=biz_type,json=bizType,proto3,enum=count.BizType" json:"biz_type,omitempty"`
	TargetType    TargetType             `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=count.TargetType" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountReq) Reset() {
	*x = GetCountReq{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountReq) ProtoMessage() {}

func (x *GetCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountReq.ProtoReflect.Descriptor instead.
func (*GetCountReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{0}
}

func (x *GetCountReq) GetBizType() BizType {
	if x != nil {
		return x.BizType
	}
	return BizType_BIZ_TYPE_UNKNOWN
}

func (x *GetCountReq) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNKNOWN
}

func (x *GetCountReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// GetCountRes 查询结果
type GetCountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountRes) Reset() {
	*x = GetCountRes{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountRes) ProtoMessage() {}

func (x *GetCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountRes.ProtoReflect.Descriptor instead.
func (*GetCountRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{1}
}

func (x *GetCountRes) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// CountKey 计数唯一键
type CountKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizType       BizType                `protobuf:"varint,1,opt,name=biz_type,json=bizType,proto3,enum=count.BizType" json:"biz_type,omitempty"`
	TargetType    TargetType             `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=count.TargetType" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountKey) Reset() {
	*x = CountKey{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountKey) ProtoMessage() {}

func (x *CountKey) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountKey.ProtoReflect.Descriptor instead.
func (*CountKey) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{2}
}

func (x *CountKey) GetBizType() BizType {
	if x != nil {
		return x.BizType
	}
	return BizType_BIZ_TYPE_UNKNOWN
}

func (x *CountKey) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNKNOWN
}

func (x *CountKey) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// BatchGetCountReq 批量查询计数
type BatchGetCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*CountKey            `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetCountReq) Reset() {
	*x = BatchGetCountReq{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetCountReq) ProtoMessage() {}

func (x *BatchGetCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetCountReq.ProtoReflect.Descriptor instead.
func (*BatchGetCountReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetCountReq) GetKeys() []*CountKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

// CountValueItem 批量查询的单项返回
type CountValueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *CountKey              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountValueItem) Reset() {
	*x = CountValueItem{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountValueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountValueItem) ProtoMessage() {}

func (x *CountValueItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountValueItem.ProtoReflect.Descriptor instead.
func (*CountValueItem) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{4}
}

func (x *CountValueItem) GetKey() *CountKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CountValueItem) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// BatchGetCountRes 批量查询结果
type BatchGetCountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CountValueItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetCountRes) Reset() {
	*x = BatchGetCountRes{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetCountRes) ProtoMessage() {}

func (x *BatchGetCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetCountRes.ProtoReflect.Descriptor instead.
func (*BatchGetCountRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetCountRes) GetItems() []*CountValueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// IncReq 对计数 +1
type IncReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizType       BizType                `protobuf:"varint,1,opt,name=biz_type,json=bizType,proto3,enum=count.BizType" json:"biz_type,omitempty"`
	TargetType    TargetType             `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=count.TargetType" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncReq) Reset() {
	*x = IncReq{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncReq) ProtoMessage() {}

func (x *IncReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncReq.ProtoReflect.Descriptor instead.
func (*IncReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{6}
}

func (x *IncReq) GetBizType() BizType {
	if x != nil {
		return x.BizType
	}
	return BizType_BIZ_TYPE_UNKNOWN
}

func (x *IncReq) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNKNOWN
}

func (x *IncReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// IncRes +1 后的计数值
type IncRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncRes) Reset() {
	*x = IncRes{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncRes) ProtoMessage() {}

func (x *IncRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncRes.ProtoReflect.Descriptor instead.
func (*IncRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{7}
}

// DecReq 对计数 -1
type DecReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizType       BizType                `protobuf:"varint,1,opt,name=biz_type,json=bizType,proto3,enum=count.BizType" json:"biz_type,omitempty"`
	TargetType    TargetType             `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=count.TargetType" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecReq) Reset() {
	*x = DecReq{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecReq) ProtoMessage() {}

func (x *DecReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecReq.ProtoReflect.Descriptor instead.
func (*DecReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{8}
}

func (x *DecReq) GetBizType() BizType {
	if x != nil {
		return x.BizType
	}
	return BizType_BIZ_TYPE_UNKNOWN
}

func (x *DecReq) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNKNOWN
}

func (x *DecReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// DecRes -1 后的计数值
type DecRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecRes) Reset() {
	*x = DecRes{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecRes) ProtoMessage() {}

func (x *DecRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecRes.ProtoReflect.Descriptor instead.
func (*DecRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{9}
}

// GetUserProfileCountsReq 查询用户主页计数
type GetUserProfileCountsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileCountsReq) Reset() {
	*x = GetUserProfileCountsReq{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileCountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileCountsReq) ProtoMessage() {}

func (x *GetUserProfileCountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileCountsReq.ProtoReflect.Descriptor instead.
func (*GetUserProfileCountsReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserProfileCountsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetUserProfileCountsRes 用户主页计数结果
type GetUserProfileCountsRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowingCount int64                  `protobuf:"varint,1,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FollowedCount  int64                  `protobuf:"varint,2,opt,name=followed_count,json=followedCount,proto3" json:"followed_count,omitempty"`
	LikeCount      int64                  `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	FavoriteCount  int64                  `protobuf:"varint,4,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	ContentCount   int64                  `protobuf:"varint,5,opt,name=content_count,json=contentCount,proto3" json:"content_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserProfileCountsRes) Reset() {
	*x = GetUserProfileCountsRes{}
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileCountsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileCountsRes) ProtoMessage() {}

func (x *GetUserProfileCountsRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_count_proto_count_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileCountsRes.ProtoReflect.Descriptor instead.
func (*GetUserProfileCountsRes) Descriptor() ([]byte, []int) {
	return file_app_rpc_count_proto_count_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserProfileCountsRes) GetFollowingCount() int64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *GetUserProfileCountsRes) GetFollowedCount() int64 {
	if x != nil {
		return x.FollowedCount
	}
	return 0
}

func (x *GetUserProfileCountsRes) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *GetUserProfileCountsRes) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *GetUserProfileCountsRes) GetContentCount() int64 {
	if x != nil {
		return x.ContentCount
	}
	return 0
}

var File_app_rpc_count_proto_count_proto protoreflect.FileDescriptor

const file_app_rpc_count_proto_count_proto_rawDesc = "" +
	"\n" +
	"\x1fapp/rpc/count/proto/count.proto\x12\x05count\"\x89\x01\n" +
	"\vGetCountReq\x12)\n" +
	"\bbiz_type\x18\x01 \x01(\x0e2\x0e.count.BizTypeR\abizType\x122\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2\x11.count.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"#\n" +
	"\vGetCountRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"\x86\x01\n" +
	"\bCountKey\x12)\n" +
	"\bbiz_type\x18\x01 \x01(\x0e2\x0e.count.BizTypeR\abizType\x122\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2\x11.count.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"7\n" +
	"\x10BatchGetCountReq\x12#\n" +
	"\x04keys\x18\x01 \x03(\v2\x0f.count.CountKeyR\x04keys\"I\n" +
	"\x0eCountValueItem\x12!\n" +
	"\x03key\x18\x01 \x01(\v2\x0f.count.CountKeyR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"?\n" +
	"\x10BatchGetCountRes\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.count.CountValueItemR\x05items\"\x84\x01\n" +
	"\x06IncReq\x12)\n" +
	"\bbiz_type\x18\x01 \x01(\x0e2\x0e.count.BizTypeR\abizType\x122\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2\x11.count.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"\b\n" +
	"\x06IncRes\"\x84\x01\n" +
	"\x06DecReq\x12)\n" +
	"\bbiz_type\x18\x01 \x01(\x0e2\x0e.count.BizTypeR\abizType\x122\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2\x11.count.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"\b\n" +
	"\x06DecRes\"2\n" +
	"\x17GetUserProfileCountsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xd4\x01\n" +
	"\x17GetUserProfileCountsRes\x12'\n" +
	"\x0ffollowing_count\x18\x01 \x01(\x03R\x0efollowingCount\x12%\n" +
	"\x0efollowed_count\x18\x02 \x01(\x03R\rfollowedCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\x03 \x01(\x03R\tlikeCount\x12%\n" +
	"\x0efavorite_count\x18\x04 \x01(\x03R\rfavoriteCount\x12#\n" +
	"\rcontent_count\x18\x05 \x01(\x03R\fcontentCount*a\n" +
	"\aBizType\x12\x14\n" +
	"\x10BIZ_TYPE_UNKNOWN\x10\x00\x12\b\n" +
	"\x04LIKE\x10\n" +
	"\x12\f\n" +
	"\bFAVORITE\x10\x14\x12\v\n" +
	"\aCOMMENT\x10\x1e\x12\f\n" +
	"\bFOLLOWED\x10(\x12\r\n" +
	"\tFOLLOWING\x10)*<\n" +
	"\n" +
	"TargetType\x12\x17\n" +
	"\x13TARGET_TYPE_UNKNOWN\x10\x00\x12\v\n" +
	"\aCONTENT\x10\n" +
	"\x12\b\n" +
	"\x04USER\x10\x142\xa9\x02\n" +
	"\x0eCounterService\x122\n" +
	"\bGetCount\x12\x12.count.GetCountReq\x1a\x12.count.GetCountRes\x12A\n" +
	"\rBatchGetCount\x12\x17.count.BatchGetCountReq\x1a\x17.count.BatchGetCountRes\x12#\n" +
	"\x03Inc\x12\r.count.IncReq\x1a\r.count.IncRes\x12#\n" +
	"\x03Dec\x12\r.count.DecReq\x1a\r.count.DecRes\x12V\n" +
	"\x14GetUserProfileCounts\x12\x1e.count.GetUserProfileCountsReq\x1a\x1e.count.GetUserProfileCountsResB\tZ\a./countb\x06proto3"

var (
	file_app_rpc_count_proto_count_proto_rawDescOnce sync.Once
	file_app_rpc_count_proto_count_proto_rawDescData []byte
)

func file_app_rpc_count_proto_count_proto_rawDescGZIP() []byte {
	file_app_rpc_count_proto_count_proto_rawDescOnce.Do(func() {
		file_app_rpc_count_proto_count_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_rpc_count_proto_count_proto_rawDesc), len(file_app_rpc_count_proto_count_proto_rawDesc)))
	})
	return file_app_rpc_count_proto_count_proto_rawDescData
}

var file_app_rpc_count_proto_count_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_app_rpc_count_proto_count_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_app_rpc_count_proto_count_proto_goTypes = []any{
	(BizType)(0),                    // 0: count.BizType
	(TargetType)(0),                 // 1: count.TargetType
	(*GetCountReq)(nil),             // 2: count.GetCountReq
	(*GetCountRes)(nil),             // 3: count.GetCountRes
	(*CountKey)(nil),                // 4: count.CountKey
	(*BatchGetCountReq)(nil),        // 5: count.BatchGetCountReq
	(*CountValueItem)(nil),          // 6: count.CountValueItem
	(*BatchGetCountRes)(nil),        // 7: count.BatchGetCountRes
	(*IncReq)(nil),                  // 8: count.IncReq
	(*IncRes)(nil),                  // 9: count.IncRes
	(*DecReq)(nil),                  // 10: count.DecReq
	(*DecRes)(nil),                  // 11: count.DecRes
	(*GetUserProfileCountsReq)(nil), // 12: count.GetUserProfileCountsReq
	(*GetUserProfileCountsRes)(nil), // 13: count.GetUserProfileCountsRes
}
var file_app_rpc_count_proto_count_proto_depIdxs = []int32{
	0,  // 0: count.GetCountReq.biz_type:type_name -> count.BizType
	1,  // 1: count.GetCountReq.target_type:type_name -> count.TargetType
	0,  // 2: count.CountKey.biz_type:type_name -> count.BizType
	1,  // 3: count.CountKey.target_type:type_name -> count.TargetType
	4,  // 4: count.BatchGetCountReq.keys:type_name -> count.CountKey
	4,  // 5: count.CountValueItem.key:type_name -> count.CountKey
	6,  // 6: count.BatchGetCountRes.items:type_name -> count.CountValueItem
	0,  // 7: count.IncReq.biz_type:type_name -> count.BizType
	1,  // 8: count.IncReq.target_type:type_name -> count.TargetType
	0,  // 9: count.DecReq.biz_type:type_name -> count.BizType
	1,  // 10: count.DecReq.target_type:type_name -> count.TargetType
	2,  // 11: count.CounterService.GetCount:input_type -> count.GetCountReq
	5,  // 12: count.CounterService.BatchGetCount:input_type -> count.BatchGetCountReq
	8,  // 13: count.CounterService.Inc:input_type -> count.IncReq
	10, // 14: count.CounterService.Dec:input_type -> count.DecReq
	12, // 15: count.CounterService.GetUserProfileCounts:input_type -> count.GetUserProfileCountsReq
	3,  // 16: count.CounterService.GetCount:output_type -> count.GetCountRes
	7,  // 17: count.CounterService.BatchGetCount:output_type -> count.BatchGetCountRes
	9,  // 18: count.CounterService.Inc:output_type -> count.IncRes
	11, // 19: count.CounterService.Dec:output_type -> count.DecRes
	13, // 20: count.CounterService.GetUserProfileCounts:output_type -> count.GetUserProfileCountsRes
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_app_rpc_count_proto_count_proto_init() }
func file_app_rpc_count_proto_count_proto_init() {
	if File_app_rpc_count_proto_count_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_rpc_count_proto_count_proto_rawDesc), len(file_app_rpc_count_proto_count_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_rpc_count_proto_count_proto_goTypes,
		DependencyIndexes: file_app_rpc_count_proto_count_proto_depIdxs,
		EnumInfos:         file_app_rpc_count_proto_count_proto_enumTypes,
		MessageInfos:      file_app_rpc_count_proto_count_proto_msgTypes,
	}.Build()
	File_app_rpc_count_proto_count_proto = out.File
	file_app_rpc_count_proto_count_proto_goTypes = nil
	file_app_rpc_count_proto_count_proto_depIdxs = nil
}
