// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: app/rpc/count/proto/count.proto

package count

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CounterService_GetCount_FullMethodName             = "/count.CounterService/GetCount"
	CounterService_BatchGetCount_FullMethodName        = "/count.CounterService/BatchGetCount"
	CounterService_Inc_FullMethodName                  = "/count.CounterService/Inc"
	CounterService_Dec_FullMethodName                  = "/count.CounterService/Dec"
	CounterService_GetUserProfileCounts_FullMethodName = "/count.CounterService/GetUserProfileCounts"
)

// CounterServiceClient is the client API for CounterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CounterServiceClient interface {
	GetCount(ctx context.Context, in *GetCountReq, opts ...grpc.CallOption) (*GetCountRes, error)
	BatchGetCount(ctx context.Context, in *BatchGetCountReq, opts ...grpc.CallOption) (*BatchGetCountRes, error)
	Inc(ctx context.Context, in *IncReq, opts ...grpc.CallOption) (*IncRes, error)
	Dec(ctx context.Context, in *DecReq, opts ...grpc.CallOption) (*DecRes, error)
	GetUserProfileCounts(ctx context.Context, in *GetUserProfileCountsReq, opts ...grpc.CallOption) (*GetUserProfileCountsRes, error)
}

type counterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCounterServiceClient(cc grpc.ClientConnInterface) CounterServiceClient {
	return &counterServiceClient{cc}
}

func (c *counterServiceClient) GetCount(ctx context.Context, in *GetCountReq, opts ...grpc.CallOption) (*GetCountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCountRes)
	err := c.cc.Invoke(ctx, CounterService_GetCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) BatchGetCount(ctx context.Context, in *BatchGetCountReq, opts ...grpc.CallOption) (*BatchGetCountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetCountRes)
	err := c.cc.Invoke(ctx, CounterService_BatchGetCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) Inc(ctx context.Context, in *IncReq, opts ...grpc.CallOption) (*IncRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncRes)
	err := c.cc.Invoke(ctx, CounterService_Inc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) Dec(ctx context.Context, in *DecReq, opts ...grpc.CallOption) (*DecRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecRes)
	err := c.cc.Invoke(ctx, CounterService_Dec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) GetUserProfileCounts(ctx context.Context, in *GetUserProfileCountsReq, opts ...grpc.CallOption) (*GetUserProfileCountsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileCountsRes)
	err := c.cc.Invoke(ctx, CounterService_GetUserProfileCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CounterServiceServer is the server API for CounterService service.
// All implementations must embed UnimplementedCounterServiceServer
// for forward compatibility.
type CounterServiceServer interface {
	GetCount(context.Context, *GetCountReq) (*GetCountRes, error)
	BatchGetCount(context.Context, *BatchGetCountReq) (*BatchGetCountRes, error)
	Inc(context.Context, *IncReq) (*IncRes, error)
	Dec(context.Context, *DecReq) (*DecRes, error)
	GetUserProfileCounts(context.Context, *GetUserProfileCountsReq) (*GetUserProfileCountsRes, error)
	mustEmbedUnimplementedCounterServiceServer()
}

// UnimplementedCounterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCounterServiceServer struct{}

func (UnimplementedCounterServiceServer) GetCount(context.Context, *GetCountReq) (*GetCountRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCount not implemented")
}
func (UnimplementedCounterServiceServer) BatchGetCount(context.Context, *BatchGetCountReq) (*BatchGetCountRes, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetCount not implemented")
}
func (UnimplementedCounterServiceServer) Inc(context.Context, *IncReq) (*IncRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Inc not implemented")
}
func (UnimplementedCounterServiceServer) Dec(context.Context, *DecReq) (*DecRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Dec not implemented")
}
func (UnimplementedCounterServiceServer) GetUserProfileCounts(context.Context, *GetUserProfileCountsReq) (*GetUserProfileCountsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfileCounts not implemented")
}
func (UnimplementedCounterServiceServer) mustEmbedUnimplementedCounterServiceServer() {}
func (UnimplementedCounterServiceServer) testEmbeddedByValue()                        {}

// UnsafeCounterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CounterServiceServer will
// result in compilation errors.
type UnsafeCounterServiceServer interface {
	mustEmbedUnimplementedCounterServiceServer()
}

func RegisterCounterServiceServer(s grpc.ServiceRegistrar, srv CounterServiceServer) {
	// If the following call panics, it indicates UnimplementedCounterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CounterService_ServiceDesc, srv)
}

func _CounterService_GetCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).GetCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterService_GetCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).GetCount(ctx, req.(*GetCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_BatchGetCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).BatchGetCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterService_BatchGetCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).BatchGetCount(ctx, req.(*BatchGetCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_Inc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).Inc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterService_Inc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).Inc(ctx, req.(*IncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_Dec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).Dec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterService_Dec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).Dec(ctx, req.(*DecReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_GetUserProfileCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileCountsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).GetUserProfileCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterService_GetUserProfileCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).GetUserProfileCounts(ctx, req.(*GetUserProfileCountsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CounterService_ServiceDesc is the grpc.ServiceDesc for CounterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CounterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "count.CounterService",
	HandlerType: (*CounterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCount",
			Handler:    _CounterService_GetCount_Handler,
		},
		{
			MethodName: "BatchGetCount",
			Handler:    _CounterService_BatchGetCount_Handler,
		},
		{
			MethodName: "Inc",
			Handler:    _CounterService_Inc_Handler,
		},
		{
			MethodName: "Dec",
			Handler:    _CounterService_Dec_Handler,
		},
		{
			MethodName: "GetUserProfileCounts",
			Handler:    _CounterService_GetUserProfileCounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/rpc/count/proto/count.proto",
}
