// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package server

import (
	"context"

	"zfeed/app/rpc/interaction/interaction"
	"zfeed/app/rpc/interaction/internal/logic/favoriteservice"
	"zfeed/app/rpc/interaction/internal/svc"
)

type FavoriteServiceServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedFavoriteServiceServer
}

func NewFavoriteServiceServer(svcCtx *svc.ServiceContext) *FavoriteServiceServer {
	return &FavoriteServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteServiceServer) Favorite(ctx context.Context, in *interaction.FavoriteReq) (*interaction.FavoriteRes, error) {
	l := favoriteservicelogic.NewFavoriteLogic(ctx, s.svcCtx)
	return l.Favorite(in)
}

func (s *FavoriteServiceServer) RemoveFavorite(ctx context.Context, in *interaction.RemoveFavoriteReq) (*interaction.RemoveFavoriteRes, error) {
	l := favoriteservicelogic.NewRemoveFavoriteLogic(ctx, s.svcCtx)
	return l.RemoveFavorite(in)
}

func (s *FavoriteServiceServer) QueryFavoriteInfo(ctx context.Context, in *interaction.QueryFavoriteInfoReq) (*interaction.QueryFavoriteInfoRes, error) {
	l := favoriteservicelogic.NewQueryFavoriteInfoLogic(ctx, s.svcCtx)
	return l.QueryFavoriteInfo(in)
}

func (s *FavoriteServiceServer) QueryFavoriteList(ctx context.Context, in *interaction.QueryFavoriteListReq) (*interaction.QueryFavoriteListRes, error) {
	l := favoriteservicelogic.NewQueryFavoriteListLogic(ctx, s.svcCtx)
	return l.QueryFavoriteList(in)
}
