
canal.instance.mysql.slaveId=1234

canal.instance.gtidon=false

canal.instance.master.address=mysql:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.tsdb.enable=true

canal.instance.dbUsername=zfeed
canal.instance.dbPassword=123456
canal.instance.connectionCharset=UTF-8

canal.instance.filter.regex=zfeed\\.(zfeed_favorite|zfeed_comment|zfeed_like|zfeed_follow|zfeed_content)

canal.mq.topic=zfeed-count-canal
canal.mq.partition=0
