// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ViewerId      *int64                 `protobuf:"varint,4,opt,name=viewer_id,json=viewerId,proto3,oneof" json:"viewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersReq) Reset() {
	*x = SearchUsersReq{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersReq) ProtoMessage() {}

func (x *SearchUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersReq.ProtoReflect.Descriptor instead.
func (*SearchUsersReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchUsersReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SearchUsersReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchUsersReq) GetViewerId() int64 {
	if x != nil && x.ViewerId != nil {
		return *x.ViewerId
	}
	return 0
}

type SearchUserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	IsFollowing   bool                   `protobuf:"varint,5,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserItem) Reset() {
	*x = SearchUserItem{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserItem) ProtoMessage() {}

func (x *SearchUserItem) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserItem.ProtoReflect.Descriptor instead.
func (*SearchUserItem) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchUserItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchUserItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SearchUserItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *SearchUserItem) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *SearchUserItem) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type SearchUsersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SearchUserItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRes) Reset() {
	*x = SearchUsersRes{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRes) ProtoMessage() {}

func (x *SearchUsersRes) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRes.ProtoReflect.Descriptor instead.
func (*SearchUsersRes) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchUsersRes) GetItems() []*SearchUserItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchUsersRes) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *SearchUsersRes) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SearchContentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ViewerId      *int64                 `protobuf:"varint,4,opt,name=viewer_id,json=viewerId,proto3,oneof" json:"viewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContentsReq) Reset() {
	*x = SearchContentsReq{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentsReq) ProtoMessage() {}

func (x *SearchContentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentsReq.ProtoReflect.Descriptor instead.
func (*SearchContentsReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchContentsReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchContentsReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SearchContentsReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchContentsReq) GetViewerId() int64 {
	if x != nil && x.ViewerId != nil {
		return *x.ViewerId
	}
	return 0
}

type SearchContentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentType   int32                  `protobuf:"varint,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	AuthorId      int64                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorName    string                 `protobuf:"bytes,4,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorAvatar  string                 `protobuf:"bytes,5,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,7,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContentItem) Reset() {
	*x = SearchContentItem{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentItem) ProtoMessage() {}

func (x *SearchContentItem) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentItem.ProtoReflect.Descriptor instead.
func (*SearchContentItem) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchContentItem) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *SearchContentItem) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *SearchContentItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *SearchContentItem) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *SearchContentItem) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

func (x *SearchContentItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchContentItem) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *SearchContentItem) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

type SearchContentsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SearchContentItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContentsRes) Reset() {
	*x = SearchContentsRes{}
	mi := &file_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentsRes) ProtoMessage() {}

func (x *SearchContentsRes) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentsRes.ProtoReflect.Descriptor instead.
func (*SearchContentsRes) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchContentsRes) GetItems() []*SearchContentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchContentsRes) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *SearchContentsRes) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x06search\"\x8b\x01\n" +
	"\x0eSearchUsersReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12 \n" +
	"\tviewer_id\x18\x04 \x01(\x03H\x00R\bviewerId\x88\x01\x01B\f\n" +
	"\n" +
	"_viewer_id\"\x92\x01\n" +
	"\x0eSearchUserItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12!\n" +
	"\fis_following\x18\x05 \x01(\bR\visFollowing\"z\n" +
	"\x0eSearchUsersRes\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.search.SearchUserItemR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x8e\x01\n" +
	"\x11SearchContentsReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12 \n" +
	"\tviewer_id\x18\x04 \x01(\x03H\x00R\bviewerId\x88\x01\x01B\f\n" +
	"\n" +
	"_viewer_id\"\x8e\x02\n" +
	"\x11SearchContentItem\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\x05R\vcontentType\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\x04 \x01(\tR\n" +
	"authorName\x12#\n" +
	"\rauthor_avatar\x18\x05 \x01(\tR\fauthorAvatar\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\a \x01(\tR\bcoverUrl\x12!\n" +
	"\fpublished_at\x18\b \x01(\x03R\vpublishedAt\"\x80\x01\n" +
	"\x11SearchContentsRes\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.search.SearchContentItemR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\x96\x01\n" +
	"\rSearchService\x12=\n" +
	"\vSearchUsers\x12\x16.search.SearchUsersReq\x1a\x16.search.SearchUsersRes\x12F\n" +
	"\x0eSearchContents\x12\x19.search.SearchContentsReq\x1a\x19.search.SearchContentsResB\n" +
	"Z\b./searchb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_search_proto_goTypes = []any{
	(*SearchUsersReq)(nil),    // 0: search.SearchUsersReq
	(*SearchUserItem)(nil),    // 1: search.SearchUserItem
	(*SearchUsersRes)(nil),    // 2: search.SearchUsersRes
	(*SearchContentsReq)(nil), // 3: search.SearchContentsReq
	(*SearchContentItem)(nil), // 4: search.SearchContentItem
	(*SearchContentsRes)(nil), // 5: search.SearchContentsRes
}
var file_search_proto_depIdxs = []int32{
	1, // 0: search.SearchUsersRes.items:type_name -> search.SearchUserItem
	4, // 1: search.SearchContentsRes.items:type_name -> search.SearchContentItem
	0, // 2: search.SearchService.SearchUsers:input_type -> search.SearchUsersReq
	3, // 3: search.SearchService.SearchContents:input_type -> search.SearchContentsReq
	2, // 4: search.SearchService.SearchUsers:output_type -> search.SearchUsersRes
	5, // 5: search.SearchService.SearchContents:output_type -> search.SearchContentsRes
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	file_search_proto_msgTypes[0].OneofWrappers = []any{}
	file_search_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
