// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package commentservice

import (
	"context"

	"zfeed/app/rpc/interaction/interaction"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetCommentsReq   = interaction.BatchGetCommentsReq
	BatchGetCommentsRes   = interaction.BatchGetCommentsRes
	BatchQueryIsLikedReq  = interaction.BatchQueryIsLikedReq
	BatchQueryIsLikedRes  = interaction.BatchQueryIsLikedRes
	BatchQueryLikeInfoReq = interaction.BatchQueryLikeInfoReq
	BatchQueryLikeInfoRes = interaction.BatchQueryLikeInfoRes
	CommentItem           = interaction.CommentItem
	CommentReq            = interaction.CommentReq
	CommentRes            = interaction.CommentRes
	DeleteCommentReq      = interaction.DeleteCommentReq
	DeleteCommentRes      = interaction.DeleteCommentRes
	FavoriteItem          = interaction.FavoriteItem
	FavoriteReq           = interaction.FavoriteReq
	FavoriteRes           = interaction.FavoriteRes
	FollowUserReq         = interaction.FollowUserReq
	FollowUserRes         = interaction.FollowUserRes
	FollowerProfile       = interaction.FollowerProfile
	GetFollowSummaryReq   = interaction.GetFollowSummaryReq
	GetFollowSummaryRes   = interaction.GetFollowSummaryRes
	IsLikedInfo           = interaction.IsLikedInfo
	LikeInfo              = interaction.LikeInfo
	LikeReq               = interaction.LikeReq
	LikeRes               = interaction.LikeRes
	ListFolloweesReq      = interaction.ListFolloweesReq
	ListFolloweesRes      = interaction.ListFolloweesRes
	ListFollowersReq      = interaction.ListFollowersReq
	ListFollowersRes      = interaction.ListFollowersRes
	PageReq               = interaction.PageReq
	PageRes               = interaction.PageRes
	QueryCommentListReq   = interaction.QueryCommentListReq
	QueryCommentListRes   = interaction.QueryCommentListRes
	QueryFavoriteInfoReq  = interaction.QueryFavoriteInfoReq
	QueryFavoriteInfoRes  = interaction.QueryFavoriteInfoRes
	QueryFavoriteListReq  = interaction.QueryFavoriteListReq
	QueryFavoriteListRes  = interaction.QueryFavoriteListRes
	QueryLikeInfoReq      = interaction.QueryLikeInfoReq
	QueryLikeInfoRes      = interaction.QueryLikeInfoRes
	QueryReplyListReq     = interaction.QueryReplyListReq
	QueryReplyListRes     = interaction.QueryReplyListRes
	RefillCommentCacheReq = interaction.RefillCommentCacheReq
	RefillCommentCacheRes = interaction.RefillCommentCacheRes
	RemoveFavoriteReq     = interaction.RemoveFavoriteReq
	RemoveFavoriteRes     = interaction.RemoveFavoriteRes
	UnfollowUserReq       = interaction.UnfollowUserReq
	UnfollowUserRes       = interaction.UnfollowUserRes
	UnlikeReq             = interaction.UnlikeReq
	UnlikeRes             = interaction.UnlikeRes

	CommentService interface {
		Comment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentRes, error)
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentRes, error)
		QueryCommentList(ctx context.Context, in *QueryCommentListReq, opts ...grpc.CallOption) (*QueryCommentListRes, error)
		QueryReplyList(ctx context.Context, in *QueryReplyListReq, opts ...grpc.CallOption) (*QueryReplyListRes, error)
		BatchGetComments(ctx context.Context, in *BatchGetCommentsReq, opts ...grpc.CallOption) (*BatchGetCommentsRes, error)
		RefillCommentCache(ctx context.Context, in *RefillCommentCacheReq, opts ...grpc.CallOption) (*RefillCommentCacheRes, error)
	}

	defaultCommentService struct {
		cli zrpc.Client
	}
)

func NewCommentService(cli zrpc.Client) CommentService {
	return &defaultCommentService{
		cli: cli,
	}
}

func (m *defaultCommentService) Comment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentRes, error) {
	client := interaction.NewCommentServiceClient(m.cli.Conn())
	return client.Comment(ctx, in, opts...)
}

func (m *defaultCommentService) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentRes, error) {
	client := interaction.NewCommentServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultCommentService) QueryCommentList(ctx context.Context, in *QueryCommentListReq, opts ...grpc.CallOption) (*QueryCommentListRes, error) {
	client := interaction.NewCommentServiceClient(m.cli.Conn())
	return client.QueryCommentList(ctx, in, opts...)
}

func (m *defaultCommentService) QueryReplyList(ctx context.Context, in *QueryReplyListReq, opts ...grpc.CallOption) (*QueryReplyListRes, error) {
	client := interaction.NewCommentServiceClient(m.cli.Conn())
	return client.QueryReplyList(ctx, in, opts...)
}

func (m *defaultCommentService) BatchGetComments(ctx context.Context, in *BatchGetCommentsReq, opts ...grpc.CallOption) (*BatchGetCommentsRes, error) {
	client := interaction.NewCommentServiceClient(m.cli.Conn())
	return client.BatchGetComments(ctx, in, opts...)
}

func (m *defaultCommentService) RefillCommentCache(ctx context.Context, in *RefillCommentCacheReq, opts ...grpc.CallOption) (*RefillCommentCacheRes, error) {
	client := interaction.NewCommentServiceClient(m.cli.Conn())
	return client.RefillCommentCache(ctx, in, opts...)
}
