// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package feedservice

import (
	"context"

	"zfeed/app/rpc/content/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticlePublishReq       = content.ArticlePublishReq
	ArticlePublishRes       = content.ArticlePublishRes
	BackfillFollowInboxReq  = content.BackfillFollowInboxReq
	BackfillFollowInboxRes  = content.BackfillFollowInboxRes
	ContentDetail           = content.ContentDetail
	ContentItem             = content.ContentItem
	DeleteContentReq        = content.DeleteContentReq
	DeleteContentRes        = content.DeleteContentRes
	EditArticleReq          = content.EditArticleReq
	EditArticleRes          = content.EditArticleRes
	EditVideoReq            = content.EditVideoReq
	EditVideoRes            = content.EditVideoRes
	FollowFeedItem          = content.FollowFeedItem
	FollowFeedReq           = content.FollowFeedReq
	FollowFeedRes           = content.FollowFeedRes
	GetContentDetailReq     = content.GetContentDetailReq
	GetContentDetailRes     = content.GetContentDetailRes
	GetUploadCredentialsReq = content.GetUploadCredentialsReq
	GetUploadCredentialsRes = content.GetUploadCredentialsRes
	OssFormData             = content.OssFormData
	RecommendFeedReq        = content.RecommendFeedReq
	RecommendFeedRes        = content.RecommendFeedRes
	UserFavoriteFeedReq     = content.UserFavoriteFeedReq
	UserFavoriteFeedRes     = content.UserFavoriteFeedRes
	UserPublishFeedReq      = content.UserPublishFeedReq
	UserPublishFeedRes      = content.UserPublishFeedRes
	VideoPublishReq         = content.VideoPublishReq
	VideoPublishRes         = content.VideoPublishRes

	FeedService interface {
		RecommendFeed(ctx context.Context, in *RecommendFeedReq, opts ...grpc.CallOption) (*RecommendFeedRes, error)
		FollowFeed(ctx context.Context, in *FollowFeedReq, opts ...grpc.CallOption) (*FollowFeedRes, error)
		UserPublishFeed(ctx context.Context, in *UserPublishFeedReq, opts ...grpc.CallOption) (*UserPublishFeedRes, error)
		UserFavoriteFeed(ctx context.Context, in *UserFavoriteFeedReq, opts ...grpc.CallOption) (*UserFavoriteFeedRes, error)
	}

	defaultFeedService struct {
		cli zrpc.Client
	}
)

func NewFeedService(cli zrpc.Client) FeedService {
	return &defaultFeedService{
		cli: cli,
	}
}

func (m *defaultFeedService) RecommendFeed(ctx context.Context, in *RecommendFeedReq, opts ...grpc.CallOption) (*RecommendFeedRes, error) {
	client := content.NewFeedServiceClient(m.cli.Conn())
	return client.RecommendFeed(ctx, in, opts...)
}

func (m *defaultFeedService) FollowFeed(ctx context.Context, in *FollowFeedReq, opts ...grpc.CallOption) (*FollowFeedRes, error) {
	client := content.NewFeedServiceClient(m.cli.Conn())
	return client.FollowFeed(ctx, in, opts...)
}

func (m *defaultFeedService) UserPublishFeed(ctx context.Context, in *UserPublishFeedReq, opts ...grpc.CallOption) (*UserPublishFeedRes, error) {
	client := content.NewFeedServiceClient(m.cli.Conn())
	return client.UserPublishFeed(ctx, in, opts...)
}

func (m *defaultFeedService) UserFavoriteFeed(ctx context.Context, in *UserFavoriteFeedReq, opts ...grpc.CallOption) (*UserFavoriteFeedRes, error) {
	client := content.NewFeedServiceClient(m.cli.Conn())
	return client.UserFavoriteFeed(ctx, in, opts...)
}
